import XCTest
@testable import NSLauncherApp

/// Reading a player's Character Showcase, and scoring them on what they
/// actually own instead of on the standardised build.
///
/// Nothing here touches the network: the wire format is pinned by a committed
/// fixture, so a change in Enka's shape shows up as a decode failure here rather
/// than as an empty import in front of a user.
final class AbyssShowcaseImportTests: XCTestCase {

    private var library: AbyssDataLibrary { AbyssDataLibraryTests.library }

    private func loadFixture() throws -> EnkaResponse {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "Fixtures/enka-showcase",
                                                  withExtension: "json"))
        return try JSONDecoder().decode(EnkaResponse.self, from: Data(contentsOf: url))
    }

    private func showcase() throws -> AbyssShowcase {
        try AbyssEnkaClient.convert(loadFixture(), uid: "618285856", map: library.gameIDs)
    }

    // MARK: - The mapping table

    /// The table is generated by `scripts/generate-abyss-game-ids.py`. If it
    /// ever ships stale, every import silently returns fewer characters, so the
    /// counts are pinned to the data it maps.
    func testGameIDMapCoversTheWholeDataSet() {
        let map = library.gameIDs
        XCTAssertEqual(Set(map.weapons.values).count, library.weapons.count,
                       "some weapons have no game id")
        XCTAssertEqual(Set(map.artifactSets.values).count, library.artifactSets.count,
                       "some artifact sets have no game id")

        // Every slug the table points at has to exist in the data.
        for slug in Array(map.characters.values) + Array(map.travelerSkillDepots.values) {
            XCTAssertNotNil(library.charactersByID[slug], "\(slug) is not a character in the data")
        }
        for slug in map.weapons.values {
            XCTAssertNotNil(library.weaponsByID[slug], "\(slug) is not a weapon in the data")
        }
        for slug in map.artifactSets.values {
            XCTAssertNotNil(library.artifactSetsByID[slug], "\(slug) is not an artifact set in the data")
        }

        // Non-Traveler characters, and the Travelers, are covered by different
        // halves of the table; between them they have to cover everyone.
        let covered = Set(map.characters.values).union(map.travelerSkillDepots.values)
        let uncovered = Set(library.characters.map(\.id)).subtracting(covered)
        XCTAssertEqual(uncovered, ["traveler-cryo"],
                       "unexpected characters have no game id — regenerate game-ids.json")
    }

    /// Every Traveler is the same avatar id; only the skill depot says which
    /// element they are. Getting this wrong would file an Anemo Traveler as a
    /// Dendro one and score them against the wrong element entirely.
    func testTravelerResolvesThroughTheSkillDepot() {
        let map = library.gameIDs
        XCTAssertEqual(map.characterID(avatarID: 10_000_005, skillDepotID: 504), "traveler-anemo")
        XCTAssertEqual(map.characterID(avatarID: 10_000_007, skillDepotID: 508), "traveler-dendro")
        XCTAssertNil(map.characterID(avatarID: 10_000_005, skillDepotID: nil))
        XCTAssertEqual(map.characterID(avatarID: 10_000_046, skillDepotID: nil), "hu-tao")
    }

    // MARK: - Decoding

    func testDecodesShowcaseIntoBuilds() throws {
        let showcase = try showcase()

        XCTAssertEqual(showcase.region, "os_euro")
        XCTAssertEqual(showcase.nickname, "Fixture")
        XCTAssertEqual(showcase.builds.map(\.characterID), ["bennett", "hu-tao"])

        let huTao = try XCTUnwrap(showcase.builds.first { $0.characterID == "hu-tao" })
        XCTAssertEqual(huTao.weaponID, "staff-of-homa")
        XCTAssertEqual(huTao.constellation, 1)
        // affixMap is 0-based, so the first refinement level is R1.
        XCTAssertEqual(huTao.weaponRefinement, 1)
        XCTAssertEqual(huTao.setPieces, ["crimson-witch-of-flames": 4])
        XCTAssertEqual(huTao.activeSetIDs, ["crimson-witch-of-flames"])

        let bennett = try XCTUnwrap(showcase.builds.first { $0.characterID == "bennett" })
        XCTAssertEqual(bennett.constellation, 6)
        XCTAssertEqual(bennett.weaponRefinement, 5)
        XCTAssertEqual(bennett.activeSetIDs, ["gladiators-finale", "noblesse-oblige"],
                       "two pairs should both count; four of one should not")
    }

    /// A character the bundled data has never heard of must be reported, not
    /// dropped: a silent skip looks identical to a showcase with fewer slots.
    func testUnknownGameIDsAreReportedRatherThanDropped() throws {
        let showcase = try showcase()
        XCTAssertEqual(showcase.unmappedIDs, ["avatar 99999999"])
        XCTAssertEqual(showcase.builds.count, 2, "the unknown avatar should not become a build")
    }

    /// `base × (1 + percent) + flat` is how the game itself computes the totals
    /// it shows, and reproducing it is the whole basis for treating these
    /// numbers as measured rather than modelled.
    func testMeasuredStatsReproduceTheGamesOwnTotals() throws {
        let response = try loadFixture()
        for avatar in try XCTUnwrap(response.avatarInfoList) {
            guard let properties = avatar.fightPropMap,
                  let reportedATK = properties["2001"], reportedATK > 0 else { continue }
            let stats = AbyssEnkaClient.measuredStats(from: properties).stats
            XCTAssertEqual(stats.atk, reportedATK, accuracy: reportedATK * 1e-3,
                           "avatar \(avatar.avatarId): computed ATK disagrees with the game's own")
        }
    }

    func testRejectsImplausibleUIDsWithoutCallingOut() {
        XCTAssertTrue(AbyssEnkaClient.isPlausibleUID("618285856"))
        XCTAssertTrue(AbyssEnkaClient.isPlausibleUID(" 8123456789 "))
        XCTAssertFalse(AbyssEnkaClient.isPlausibleUID("12345"))
        XCTAssertFalse(AbyssEnkaClient.isPlausibleUID("0123456789"))
        XCTAssertFalse(AbyssEnkaClient.isPlausibleUID("61828585a"))
        XCTAssertFalse(AbyssEnkaClient.isPlausibleUID(""))
    }

    func testEmptyShowcaseIsAnErrorWithSomethingToActOn() throws {
        let payload = EnkaResponse(playerInfo: nil, avatarInfoList: [], ttl: 60, uid: "1", region: nil)
        XCTAssertThrowsError(try AbyssEnkaClient.convert(payload, uid: "618285856",
                                                         map: library.gameIDs)) { error in
            XCTAssertEqual(error as? AbyssEnkaError, .showcaseEmpty)
        }
    }

    // MARK: - Scoring on real stats

    /// The measured sheet has the player's set bonuses already baked in. To
    /// compare it against a set they could wear instead, those have to come back
    /// out first — otherwise the comparison double-counts one side.
    func testTakingASetBackOutOfAMeasuredSheetIsExactlyReversible() throws {
        let tuning = try XCTUnwrap(library.tuning)
        let assembler = AbyssBuildAssembler(tuning: tuning, moonsignIDs: library.moonsignIDs,
                                            artifactSets: library.artifactSets)
        let build = try XCTUnwrap(showcase().builds.first { $0.characterID == "hu-tao" })
        let character = try XCTUnwrap(library.charactersByID["hu-tao"])
        let worn = build.activeSetIDs.compactMap { library.artifactSetsByID[$0] }

        let measured = build.stats.stats
        var rebuilt = assembler.showcaseStats(build: build, character: character, weapon: nil,
                                              wornSets: worn)
        var diagnostics = AbyssParseDiagnostics()
        assembler.applySets(worn, character: character, to: &rebuilt, diagnostics: &diagnostics)

        // Putting the same set back must land on the measured numbers again,
        // apart from the conditional part the game screen never showed.
        XCTAssertEqual(rebuilt.atkPercent, measured.atkPercent, accuracy: 1e-9)
        XCTAssertEqual(rebuilt.critRate, measured.critRate, accuracy: 1e-9)
        XCTAssertGreaterThanOrEqual(rebuilt.elementalBonus(.pyro), measured.elementalBonus(.pyro))
    }

    /// Everyone is scored at level 90, imported or not. Without this an account
    /// mid-way through levelling would be ranked on how far along it is rather
    /// than on what its builds can do, and an imported character at 80 would
    /// lose to a modelled one at 90 purely for being imported.
    func testImportedBuildsAreScoredAtLevelNinety() throws {
        let tuning = try XCTUnwrap(library.tuning)
        let assembler = AbyssBuildAssembler(tuning: tuning, moonsignIDs: library.moonsignIDs,
                                            artifactSets: library.artifactSets)
        let character = try XCTUnwrap(library.charactersByID["hu-tao"])
        let build = try XCTUnwrap(showcase().builds.first { $0.characterID == "hu-tao" })
        let homa = try XCTUnwrap(library.weaponsByID["staff-of-homa"])

        let atLv90 = assembler.showcaseStats(build: build, character: character, weapon: homa,
                                             wornSets: [])
        XCTAssertEqual(atLv90.baseATK,
                       try XCTUnwrap(character.baseStats.lv90.atk) + XCTUnwrap(homa.atkLv90),
                       accuracy: 1e-9,
                       "base ATK should be the character and weapon at 90, not at the account's level")
        XCTAssertEqual(atLv90.baseHP, try XCTUnwrap(character.baseStats.lv90.hp), accuracy: 1e-9)
        XCTAssertEqual(atLv90.baseDEF, try XCTUnwrap(character.baseStats.lv90.def), accuracy: 1e-9)

        // Nothing else is invented: the rolls stay exactly as measured.
        XCTAssertEqual(atLv90.critDMG, build.stats.stats.critDMG, accuracy: 1e-9)

        // And a build at a lower level lands on the same base numbers.
        let lowered = AbyssShowcaseBuild(
            characterID: build.characterID, level: 70, constellation: build.constellation,
            weaponID: build.weaponID, weaponLevel: 70, weaponRefinement: build.weaponRefinement,
            setPieces: build.setPieces, stats: AbyssMeasuredStats())
        let loweredStats = assembler.showcaseStats(build: lowered, character: character,
                                                   weapon: homa, wornSets: [])
        XCTAssertEqual(loweredStats.baseATK, atLv90.baseATK, accuracy: 1e-9,
                       "a level-70 import should still be scored at 90")
    }

    /// A measured sheet never contains what the character hands the *party* —
    /// the game screen shows only what they keep — so there is nothing to take
    /// back out when the set effects are stripped.
    ///
    /// Subtracting them anyway left the sheet granting a negative party buff,
    /// and because the artifact advisor then dresses this character in some
    /// other set, that negative reached the team score: an imported Noblesse
    /// Oblige wearer moved to another set handed the whole party -20% ATK.
    func testStrippingSetsFromAMeasuredSheetLeavesNoNegativePartyBuff() throws {
        let tuning = try XCTUnwrap(library.tuning)
        let assembler = AbyssBuildAssembler(tuning: tuning, moonsignIDs: library.moonsignIDs,
                                            artifactSets: library.artifactSets,
                                            talentPartyBuffs: library.talentPartyBuffsByCharacterID)
        let character = try XCTUnwrap(library.charactersByID["hu-tao"])
        let noblesse = try XCTUnwrap(library.artifactSetsByID["noblesse-oblige"])

        let build = AbyssShowcaseBuild(characterID: "hu-tao", level: 90, constellation: 0,
                                       weaponID: nil, weaponLevel: 90, weaponRefinement: 1,
                                       setPieces: ["noblesse-oblige": 4], stats: AbyssMeasuredStats())
        let base = assembler.showcaseStats(build: build, character: character, weapon: nil,
                                           wornSets: [noblesse])
        XCTAssertEqual(base.partyATKPercent, 0, accuracy: 1e-9,
                       "stripping the set left a negative party ATK buff")

        // Putting a different set on must give that set's party buff and only
        // that set's — not this one's, and not a leftover debt from it.
        var swapped = base
        var diagnostics = AbyssParseDiagnostics()
        let crimson = try XCTUnwrap(library.artifactSetsByID["crimson-witch-of-flames"])
        assembler.applySets([crimson], character: character, to: &swapped, diagnostics: &diagnostics)
        XCTAssertGreaterThanOrEqual(swapped.partyATKPercent, 0,
                                    "an imported character handed the party a negative ATK buff")

        // And wearing the same set again reproduces its party buff exactly.
        var kept = base
        assembler.applySets([noblesse], character: character, to: &kept, diagnostics: &diagnostics)
        XCTAssertGreaterThan(kept.partyATKPercent, 0, "the set's own party buff went missing")
    }

    func testImportedCharactersAreScoredOnTheirOwnGear() async throws {
        let optimizer = try XCTUnwrap(AbyssOptimizer(library: library))
        let builds = try showcase().builds
        var roster = AbyssRoster.empty
        roster.characters = (builds.map(\.characterID) + ["diona", "fischl"]).map { .init(id: $0) }
        roster.weapons = builds.compactMap(\.weaponID).map { .init(id: $0) }

        let output = await optimizer.run(AbyssOptimizerRequest(roster: roster, floors: [12], topN: 3,
                                                               showcase: builds))
        let team = try XCTUnwrap(output.reports.first?.teams.first)

        let huTao = try XCTUnwrap(team.assignment["hu-tao"])
        XCTAssertEqual(huTao.statSource, .measured)
        XCTAssertEqual(huTao.weaponID, "staff-of-homa",
                       "an imported character keeps the weapon they actually hold")

        let diona = try XCTUnwrap(team.assignment["diona"])
        XCTAssertEqual(diona.statSource, .modelled)

        XCTAssertTrue(team.notes.contains(.mixedStatSources),
                      "a team mixing measured and modelled builds has to say so")
    }

    /// The point of importing: the advice stops being "wear this set" and
    /// becomes "this beats what you are wearing, by this much".
    func testAdviceComparesAgainstWhatThePlayerIsWearing() async throws {
        let optimizer = try XCTUnwrap(AbyssOptimizer(library: library))
        let builds = try showcase().builds
        var roster = AbyssRoster.empty
        roster.characters = (builds.map(\.characterID) + ["diona", "fischl"]).map { .init(id: $0) }
        roster.weapons = builds.compactMap(\.weaponID).map { .init(id: $0) }

        let output = await optimizer.run(AbyssOptimizerRequest(roster: roster, floors: [12], topN: 3,
                                                               showcase: builds))
        for team in try XCTUnwrap(output.reports.first?.teams) {
            for build in builds {
                guard let advice = team.artifactAdvice[build.characterID] else { continue }
                if advice.currentSetIDs.isEmpty {
                    XCTAssertEqual(advice.setIDs, build.activeSetIDs,
                                   "\(build.characterID): no upgrade shown, so the advice should be their own set")
                } else {
                    XCTAssertEqual(advice.currentSetIDs, build.activeSetIDs,
                                   "\(build.characterID): the 'currently wearing' set is not theirs")
                    XCTAssertNotEqual(advice.setIDs, advice.currentSetIDs)
                    XCTAssertGreaterThanOrEqual(advice.upgradeOverCurrent, 0)
                }
            }
        }
    }
}
