import Foundation
import SwiftUI

/// UI-facing snapshot of the currently running launcher operation.
struct OperationProgress: Equatable {
    var stageTitle: String
    var itemPath: String?
    var itemPaths: [String]? = nil
    var partText: String?
    var detailText: String?
    var resumePointText: String? = nil
    var fractionCompleted: Double?
    var isIndeterminate: Bool
    var currentPartDetailText: String?
    var currentPartFractionCompleted: Double?
    var currentPartIsIndeterminate: Bool
    var speedText: String?
    var etaText: String?
    var isETAWarmingUp: Bool = false
    var totalKBText: String?
    var currentPartKBText: String?
}

/// Main application view model that connects SwiftUI state to launcher services.
@MainActor
final class LauncherViewModel: ObservableObject {
    /// Persisted user configuration currently displayed by the UI.
    @Published var settings: AppSettings
    /// Primary status line shown in the main window.
    @Published var statusText: String
    /// Last human-readable plan summary generated by the planner.
    @Published var lastPlanSummary = ""
    /// True while an install or launch task is active.
    @Published var isBusy = false
    /// Localized error message displayed in the alert.
    @Published var errorMessage: String?
    /// Structured progress displayed by the status panel.
    @Published var operationProgress: OperationProgress?
    /// True when a running or resumable operation is paused.
    @Published var isPaused = false
    /// True while the selected game is being launched through Wine.
    @Published var isLaunchingWithWine = false
    /// Streaming diagnostic log for the latest Wine launch.
    @Published var wineRunLog = ""
    /// Streaming diagnostic log for the latest game update.
    @Published var updateRunLog = ""
    /// True while the selected game is being updated from a manifest.
    @Published var isUpdatingGame = false

    private let coordinator: LauncherCoordinator
    private var currentTask: Task<Void, Never>?
    private var operationController: OperationController?
    private var resumableDownloadGameID: String?
    private var lastTransferMetricsUpdateAt: Date?
    private var displayedSpeedText: String?
    private var displayedEtaText: String?
    private var transferSamples: [TransferSample] = []
    private var lastDownloadFieldsUpdateAt: Date?
    private var displayedDownloadFields: DownloadFieldSnapshot?
    private var activeManifestItems: [String: Date] = [:]
    private var isSkippingMoltenVKExtensionDump = false
    private var didSummarizeMoltenVKDump = false
    private var lastUpdateLogOverallBucket: Int?
    private var updateLoggedCompletedFiles: Set<String> = []

    /// Creates a view model with already-loaded settings and a configured coordinator.
    init(settings: AppSettings, coordinator: LauncherCoordinator) {
        self.settings = settings
        self.statusText = AppText(language: settings.language).ready
        self.coordinator = coordinator
        restorePersistedDownloadStateIfNeeded()
    }

    /// Builds the production dependency graph and loads settings for app startup.
    static func bootstrap() -> LauncherViewModel {
        let processRunner = ProcessRunner()
        let coordinator = LauncherCoordinator(
            settingsStore: SettingsStore(),
            downloadStateStore: DownloadStateStore(),
            manifestInstaller: ManifestInstaller(),
            genshinStreamingMetadataService: GenshinStreamingMetadataService(),
            sophonInstaller: GenshinSophonInstaller(),
            packageDownloader: PackageDownloadService(),
            archiveInstaller: ArchiveInstaller(processRunner: processRunner),
            importService: ImportService(),
            wineService: WineService(processRunner: processRunner)
        )

        let loadedSettings = (try? coordinator.loadSettings()) ?? .default
        let settings = loadedSettings.applyingBundledGenshinDefaultsIfNeeded()
        if settings != loadedSettings {
            try? coordinator.saveSettings(settings)
        }
        return LauncherViewModel(settings: settings, coordinator: coordinator)
    }

    /// Games configured in settings.
    var games: [GameDefinition] { settings.games }

    /// Currently selected game; this app currently exposes the first configured game.
    var selectedGame: GameDefinition? {
        games.first
    }

    /// Display name of the selected package source.
    var selectedGamePackageName: String {
        guard let game = selectedGame else { return text.noPackageConfigured }
        if game.installerStrategy == .streamingManifest {
            return text.officialStreamingSource
        }
        return game.packageSource?.archiveFileName ?? text.noPackageConfigured
    }

    /// Whether the selected game has enough remote metadata to start a download.
    var canDownloadSelectedGame: Bool {
        guard let game = selectedGame else { return false }
        switch game.installerStrategy {
        case .streamingManifest:
            return true
        case .manifest:
            return game.manifestURL != nil
        case .archivePackage:
            guard let packageSource = game.packageSource else { return false }
            return packageSource.remoteURL != nil || !(packageSource.partURLs?.isEmpty ?? true)
        case .existingInstall:
            return false
        }
    }

    /// Whether the UI can offer a local archive picker for the selected game.
    var canInstallFromLocalArchive: Bool {
        selectedGame?.installerStrategy == .archivePackage
    }

    /// Whether the selected game can be updated from a remote manifest.
    var canUpdateSelectedGame: Bool {
        guard let game = selectedGame else { return false }
        switch game.installerStrategy {
        case .manifest:
            return game.manifestURL != nil
        case .streamingManifest:
            return true
        case .archivePackage, .existingInstall:
            return false
        }
    }

    /// Localized text helper derived from the current setting.
    var text: AppText {
        AppText(language: settings.language)
    }

    /// Persists settings and surfaces any write error to the UI.
    func persistSettings() {
        do {
            try coordinator.saveSettings(settings)
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    /// Updates the UI language and persists the choice.
    func setLanguage(_ language: AppLanguage) {
        settings.language = language
        statusText = AppText(language: language).ready
        persistSettings()
    }

    /// Updates whether Wine launches should request a windowed or fullscreen game surface.
    func setLaunchDisplayMode(_ mode: LaunchDisplayMode) {
        settings.launchDisplayMode = mode
        persistSettings()
    }

    /// Builds an install plan for the selected game.
    func refreshPlan() {
        guard let game = selectedGame else { return }
        resetTransferMetricsDisplay()
        resetActiveManifestItems()
        currentTask?.cancel()
        isBusy = true
        isPaused = false
        operationController = OperationController()
        operationProgress = OperationProgress(
            stageTitle: text.planInstallTitle,
            itemPath: game.displayName,
            partText: nil,
            detailText: nil,
            fractionCompleted: nil,
            isIndeterminate: true,
            currentPartDetailText: nil,
            currentPartFractionCompleted: nil,
            currentPartIsIndeterminate: true,
            speedText: nil,
            etaText: nil,
            totalKBText: nil,
            currentPartKBText: nil
        )
        statusText = text.planningInstall(for: game.displayName)
        errorMessage = nil

        currentTask = Task { [weak self] in
            guard let self else { return }
            defer {
                self.isBusy = false
                self.isPaused = false
                self.currentTask = nil
                self.operationController = nil
            }
            do {
                let plan = try await coordinator.fetchInstallPlan(for: game, settings: self.settings)
                lastPlanSummary = text.installPlanSummary(
                    version: plan.version,
                    download: ByteCountFormatter.string(fromByteCount: plan.estimatedBytesToDownload, countStyle: .file),
                    peakTemp: ByteCountFormatter.string(fromByteCount: plan.peakTemporaryBytes, countStyle: .file),
                    steps: plan.steps.count
                )
                statusText = text.installPlanReady
                operationProgress = OperationProgress(
                    stageTitle: text.planInstallTitle,
                    itemPath: game.displayName,
                    partText: nil,
                    detailText: text.installPlanReady,
                    fractionCompleted: 1,
                    isIndeterminate: false,
                    currentPartDetailText: nil,
                    currentPartFractionCompleted: nil,
                    currentPartIsIndeterminate: false,
                    speedText: nil,
                    etaText: nil,
                    totalKBText: nil,
                    currentPartKBText: nil
                )
            } catch {
                if error is CancellationError {
                    self.statusText = self.text.operationStopped
                } else {
                    self.errorMessage = self.localizedErrorMessage(for: error)
                    self.statusText = self.text.failedToPlanInstall
                }
                self.operationProgress = nil
            }
        }
    }

    /// Installs the selected game from either the configured remote package or a local archive override.
    func installSelectedGame(archiveOverrideURL: URL? = nil) {
        guard let game = selectedGame else { return }
        resetTransferMetricsDisplay()
        resetActiveManifestItems()
        resumableDownloadGameID = nil
        currentTask?.cancel()
        isBusy = true
        isPaused = false
        operationController = OperationController()
        operationProgress = OperationProgress(
            stageTitle: text.downloadInstallTitle,
            itemPath: archiveOverrideURL?.lastPathComponent ?? selectedGamePackageName,
            partText: nil,
            detailText: archiveOverrideURL == nil ? text.connectingToServer : text.waitingForProgress,
            fractionCompleted: nil,
            isIndeterminate: archiveOverrideURL != nil,
            currentPartDetailText: nil,
            currentPartFractionCompleted: nil,
            currentPartIsIndeterminate: true,
            speedText: nil,
            etaText: nil,
            totalKBText: nil,
            currentPartKBText: nil
        )
        statusText = archiveOverrideURL == nil
            ? text.installing(game.displayName)
            : text.installingFromArchive(game.displayName, archiveName: archiveOverrideURL!.lastPathComponent)
        errorMessage = nil

        currentTask = Task { [weak self] in
            guard let self else { return }
            var shouldKeepPausedState = false
            defer {
                if shouldKeepPausedState {
                    self.currentTask = nil
                    self.operationController = nil
                } else {
                    self.isBusy = false
                    self.isPaused = false
                    self.resumableDownloadGameID = nil
                    self.currentTask = nil
                    self.operationController = nil
                }
            }
            do {
                try await self.coordinator.installGame(
                    game,
                    settings: self.settings,
                    archiveOverrideURL: archiveOverrideURL,
                    operationController: self.operationController
                ) { [weak self] event in
                    await MainActor.run {
                        self?.apply(event: event)
                    }
                }
                self.statusText = self.text.installCompleted
                self.operationProgress = OperationProgress(
                    stageTitle: self.text.downloadInstallTitle,
                    itemPath: game.displayName,
                    partText: nil,
                    detailText: self.text.installCompleted,
                    fractionCompleted: 1,
                    isIndeterminate: false,
                    currentPartDetailText: nil,
                    currentPartFractionCompleted: nil,
                    currentPartIsIndeterminate: false,
                    speedText: nil,
                    etaText: nil,
                    totalKBText: nil,
                    currentPartKBText: nil
                )
            } catch {
                if let interruption = error as? PackageDownloadInterruption, interruption == .paused {
                    // A paused download keeps the UI busy so the Resume action can continue it later.
                    shouldKeepPausedState = true
                    if let state = try? self.coordinator.loadPersistedDownloadState(for: game.id) {
                        self.applyPersistedDownloadState(state, for: game.id)
                    }
                } else if error is CancellationError {
                    self.statusText = self.text.operationStopped
                    self.operationProgress = nil
                } else {
                    self.errorMessage = self.localizedErrorMessage(for: error)
                    self.statusText = self.text.installFailed
                    self.operationProgress = nil
                }
            }
        }
    }

    /// Updates the selected manifest-backed game by downloading only missing or changed files.
    func updateSelectedGame() {
        guard let game = selectedGame, canUpdateSelectedGame else { return }
        resetTransferMetricsDisplay()
        resetActiveManifestItems()
        resumableDownloadGameID = nil
        currentTask?.cancel()
        isBusy = true
        isPaused = false
        isUpdatingGame = true
        updateRunLog = ""
        lastUpdateLogOverallBucket = nil
        updateLoggedCompletedFiles.removeAll()
        operationController = OperationController()
        operationProgress = OperationProgress(
            stageTitle: text.updateGameTitle,
            itemPath: game.displayName,
            partText: nil,
            detailText: text.checkingForUpdates(game.displayName),
            fractionCompleted: nil,
            isIndeterminate: true,
            currentPartDetailText: nil,
            currentPartFractionCompleted: nil,
            currentPartIsIndeterminate: true,
            speedText: nil,
            etaText: nil,
            totalKBText: nil,
            currentPartKBText: nil
        )
        statusText = text.checkingForUpdates(game.displayName)
        errorMessage = nil
        appendUpdateLogLine(logText(en: "Update \(game.displayName)", vi: "Cập nhật \(game.displayName)"))
        appendUpdateLogLine(logText(en: "Strategy: \(game.installerStrategy.rawValue)", vi: "Chiến lược: \(game.installerStrategy.rawValue)"))
        appendUpdateLogLine(logText(en: "Install directory: \(game.installDirectory.path)", vi: "Thư mục cài đặt: \(game.installDirectory.path)"))
        appendUpdateLogLine(logText(en: "Executable: \(game.executableRelativePath)", vi: "File chạy: \(game.executableRelativePath)"))
        appendUpdateLogLine(logText(en: "Runtime requirements: \(game.runtimeRequirements.map(\.rawValue).joined(separator: ", "))", vi: "Runtime cần có: \(game.runtimeRequirements.map(\.rawValue).joined(separator: ", "))"))
        appendUpdateLogLine(logText(en: "---- check latest manifest ----", vi: "---- kiểm tra manifest mới nhất ----"))

        currentTask = Task { [weak self] in
            guard let self else { return }
            defer {
                self.isBusy = false
                self.isPaused = false
                self.isUpdatingGame = false
                self.currentTask = nil
                self.operationController = nil
            }
            do {
                let plan = try await self.coordinator.fetchUpdatePlan(for: game, settings: self.settings)
                let currentVersion = plan.installedVersion ?? self.text.missingVersionLabel
                let downloadText = ByteCountFormatter.string(fromByteCount: plan.bytesToDownload, countStyle: .file)
                let summary = self.text.updatePlanSummary(
                    currentVersion: currentVersion,
                    latestVersion: plan.latestVersion,
                    download: downloadText,
                    files: plan.changedItemCount,
                    skipped: plan.skippedItemCount
                )
                self.lastPlanSummary = summary
                self.appendUpdateLogLine(self.logText(en: "Update source: \(plan.sourceKind.rawValue)", vi: "Nguồn cập nhật: \(plan.sourceKind.rawValue)"))
                self.appendUpdateLogLine(self.logText(en: "Installed version: \(currentVersion)", vi: "Phiên bản hiện tại: \(currentVersion)"))
                self.appendUpdateLogLine(self.logText(en: "Latest version: \(plan.latestVersion)", vi: "Phiên bản mới nhất: \(plan.latestVersion)"))
                self.appendUpdateLogLine(self.logText(en: "Items to update: \(plan.changedItemCount)", vi: "Mục cần cập nhật: \(plan.changedItemCount)"))
                self.appendUpdateLogLine(self.logText(en: "Items already valid: \(plan.skippedItemCount)", vi: "Mục đã hợp lệ: \(plan.skippedItemCount)"))
                self.appendUpdateLogLine(self.logText(en: "Bytes to download: \(downloadText)", vi: "Dung lượng cần tải: \(downloadText)"))
                if plan.sourceKind == .sophon {
                    self.appendUpdateLogLine(self.logText(
                        en: "Existing Sophon assets are resolved locally by size and MD5 before chunk downloads.",
                        vi: "Asset Sophon đã có được đối chiếu local bằng size và MD5 trước khi tải chunk."
                    ))
                    self.appendUpdateLogLine(self.logText(
                        en: "Sophon downloader: high-concurrency chunk requests, in-process zstd, batched resume state.",
                        vi: "Bộ tải Sophon: tải nhiều chunk song song, giải nén zstd trong tiến trình, gom batch trạng thái resume."
                    ))
                    self.appendUpdateLogLine(self.logText(
                        en: "Bytes to write after decompression: \(ByteCountFormatter.string(fromByteCount: plan.decompressedBytesToWrite, countStyle: .file))",
                        vi: "Dung lượng ghi sau giải nén: \(ByteCountFormatter.string(fromByteCount: plan.decompressedBytesToWrite, countStyle: .file))"
                    ))
                }
                self.appendUpdateLogLine(self.logText(en: "Peak temporary bytes: \(ByteCountFormatter.string(fromByteCount: plan.peakTemporaryBytes, countStyle: .file))", vi: "Bộ nhớ tạm tối đa: \(ByteCountFormatter.string(fromByteCount: plan.peakTemporaryBytes, countStyle: .file))"))
                self.appendUpdateLogLine(self.logText(en: "Metadata rewrite needed: \(plan.metadataNeedsUpdate ? "yes" : "no")", vi: "Cần ghi lại metadata: \(plan.metadataNeedsUpdate ? "có" : "không")"))
                self.appendPlannedUpdateItemsToLog(plan)

                if plan.isUpToDate {
                    self.statusText = self.text.gameUpToDate(plan.latestVersion)
                    self.appendUpdateLogLine(self.logText(en: "---- up to date ----", vi: "---- đã là bản mới nhất ----"))
                    self.appendUpdateLogLine(self.text.gameUpToDate(plan.latestVersion))
                    self.operationProgress = OperationProgress(
                        stageTitle: self.text.updateGameTitle,
                        itemPath: game.displayName,
                        partText: nil,
                        detailText: self.text.gameUpToDate(plan.latestVersion),
                        fractionCompleted: 1,
                        isIndeterminate: false,
                        currentPartDetailText: nil,
                        currentPartFractionCompleted: nil,
                        currentPartIsIndeterminate: false,
                        speedText: nil,
                        etaText: nil,
                        totalKBText: nil,
                        currentPartKBText: nil
                    )
                    return
                }

                self.statusText = self.text.updating(game.displayName)
                self.appendUpdateLogLine(self.logText(en: "---- apply delta ----", vi: "---- áp dụng phần cần cập nhật ----"))
                self.operationProgress = OperationProgress(
                    stageTitle: self.text.updateGameTitle,
                    itemPath: game.displayName,
                    partText: nil,
                    detailText: summary,
                    fractionCompleted: plan.bytesToDownload > 0 ? 0 : nil,
                    isIndeterminate: plan.bytesToDownload <= 0,
                    currentPartDetailText: nil,
                    currentPartFractionCompleted: nil,
                    currentPartIsIndeterminate: true,
                    speedText: nil,
                    etaText: nil,
                    totalKBText: self.text.progressValueKB(
                        receivedKB: "0",
                        totalKB: String(plan.bytesToDownload / 1024)
                    ),
                    currentPartKBText: nil
                )

                try await self.coordinator.updateGame(
                    game,
                    settings: self.settings,
                    plan: plan,
                    operationController: self.operationController
                ) { [weak self] event in
                    await MainActor.run {
                        self?.apply(event: event)
                    }
                }

                self.statusText = self.text.updateCompleted
                self.appendUpdateLogLine(self.logText(en: "---- update completed ----", vi: "---- cập nhật hoàn tất ----"))
                self.appendUpdateLogLine(self.text.updatedVersion(plan.latestVersion))
                self.operationProgress = OperationProgress(
                    stageTitle: self.text.updateGameTitle,
                    itemPath: game.displayName,
                    partText: nil,
                    detailText: self.text.updatedVersion(plan.latestVersion),
                    fractionCompleted: 1,
                    isIndeterminate: false,
                    currentPartDetailText: nil,
                    currentPartFractionCompleted: nil,
                    currentPartIsIndeterminate: false,
                    speedText: nil,
                    etaText: nil,
                    totalKBText: nil,
                    currentPartKBText: nil
                )
            } catch {
                if error is CancellationError {
                    self.statusText = self.text.operationStopped
                    self.appendUpdateLogLine(self.logText(en: "---- update stopped ----", vi: "---- đã dừng cập nhật ----"))
                } else {
                    let message = self.localizedErrorMessage(for: error)
                    self.errorMessage = message
                    self.statusText = self.text.updateFailed
                    self.appendUpdateLogLine(self.logText(en: "---- update failed ----", vi: "---- cập nhật thất bại ----"))
                    self.appendUpdateLogLine(message)
                }
                self.operationProgress = nil
            }
        }
    }

    /// Updates the selected game install root and derived Wine prefix path.
    func setInstallDirectoryForSelectedGame(_ url: URL) {
        updateSelectedGame { game in
            game.installDirectory = url
            game.winePrefixDirectory = url.appendingPathComponent(".wine", isDirectory: true)
        }
        persistSettings()
    }

    /// Updates the executable path relative to the install root.
    func setExecutableRelativePathForSelectedGame(_ path: String) {
        updateSelectedGame { game in
            game.executableRelativePath = path
        }
        persistSettings()
    }

    /// Updates the archive file name while preserving the rest of the package source.
    func setArchiveFileNameForSelectedGame(_ fileName: String) {
        updateSelectedGame { game in
            let current = game.packageSource ?? PackageSource(
                remoteURL: nil,
                partURLs: nil,
                archiveFileName: fileName,
                archiveFormat: .sevenZip,
                expectedArchiveSize: nil
            )
            game.packageSource = PackageSource(
                remoteURL: current.remoteURL,
                partURLs: current.partURLs,
                archiveFileName: fileName,
                archiveFormat: current.archiveFormat,
                expectedArchiveSize: current.expectedArchiveSize
            )
        }
        persistSettings()
    }

    /// Sets the single-file remote package URL for the selected game.
    func setPackageURLForSelectedGame(_ url: URL) {
        updateSelectedGame { current in
            let packageSource = current.packageSource ?? PackageSource(
                remoteURL: nil,
                partURLs: nil,
                archiveFileName: "package.7z",
                archiveFormat: .sevenZip,
                expectedArchiveSize: nil
            )
            current.packageSource = PackageSource(
                remoteURL: url,
                partURLs: packageSource.partURLs,
                archiveFileName: packageSource.archiveFileName,
                archiveFormat: packageSource.archiveFormat,
                expectedArchiveSize: packageSource.expectedArchiveSize
            )
        }
        persistSettings()
    }

    /// Sets multipart package URLs and switches the package source to multipart mode.
    func setPartURLsForSelectedGame(_ urls: [URL]) {
        updateSelectedGame { current in
            let packageSource = current.packageSource ?? PackageSource(
                remoteURL: urls.first,
                partURLs: urls,
                archiveFileName: urls.first?.lastPathComponent ?? "package.zip.001",
                archiveFormat: .multipartZip,
                expectedArchiveSize: nil
            )
            current.packageSource = PackageSource(
                remoteURL: urls.first ?? packageSource.remoteURL,
                partURLs: urls.isEmpty ? nil : urls,
                archiveFileName: urls.first?.lastPathComponent ?? packageSource.archiveFileName,
                archiveFormat: urls.isEmpty ? packageSource.archiveFormat : .multipartZip,
                expectedArchiveSize: packageSource.expectedArchiveSize
            )
        }
        persistSettings()
    }

    /// Removes only the single remote URL from the selected package source.
    func clearPackageURLForSelectedGame() {
        guard let game = selectedGame, let packageSource = game.packageSource else { return }
        updateSelectedGame { current in
            current.packageSource = PackageSource(
                remoteURL: nil,
                partURLs: packageSource.partURLs,
                archiveFileName: packageSource.archiveFileName,
                archiveFormat: packageSource.archiveFormat,
                expectedArchiveSize: packageSource.expectedArchiveSize
            )
        }
        persistSettings()
    }

    /// Changes the package archive format while keeping existing source metadata.
    func setArchiveFormatForSelectedGame(_ format: ArchiveFormat) {
        updateSelectedGame { game in
            let current = game.packageSource ?? PackageSource(
                remoteURL: nil,
                partURLs: nil,
                archiveFileName: "package.\(format.fileExtensionHint)",
                archiveFormat: format,
                expectedArchiveSize: nil
            )
            game.packageSource = PackageSource(
                remoteURL: current.remoteURL,
                partURLs: current.partURLs,
                archiveFileName: current.archiveFileName,
                archiveFormat: format,
                expectedArchiveSize: current.expectedArchiveSize
            )
        }
        persistSettings()
    }

    /// Launches the selected game through Wine.
    func launchSelectedGame() {
        guard let game = selectedGame else { return }
        resetTransferMetricsDisplay()
        currentTask?.cancel()
        isBusy = true
        isPaused = false
        isLaunchingWithWine = true
        wineRunLog = ""
        isSkippingMoltenVKExtensionDump = false
        didSummarizeMoltenVKDump = false
        operationController = OperationController()
        operationProgress = OperationProgress(
            stageTitle: text.launchTitle,
            itemPath: game.executableRelativePath,
            partText: nil,
            detailText: nil,
            fractionCompleted: nil,
            isIndeterminate: true,
            currentPartDetailText: nil,
            currentPartFractionCompleted: nil,
            currentPartIsIndeterminate: true,
            speedText: nil,
            etaText: nil,
            totalKBText: nil,
            currentPartKBText: nil
        )
        statusText = text.launching(game.displayName)
        errorMessage = nil
        appendWineLogLine("Launching \(game.displayName)")
        appendWineLogLine("Wine: \(settings.wineBinaryPath)")
        appendWineLogLine("Prefix: \(game.winePrefixDirectory.path)")
        appendWineLogLine("Working directory: \(game.installDirectory.path)")
        appendWineLogLine("Executable: \(game.installDirectory.appendingPathComponent(game.executableRelativePath).path)")
        appendWineLogLine("Display mode: \(settings.launchDisplayMode.rawValue)")
        if !game.runtimeRequirements.isEmpty {
            appendWineLogLine("Runtime requirements: \(game.runtimeRequirements.map(\.rawValue).joined(separator: ", "))")
        }
        let effectiveArguments = settings.launchArguments(for: game)
        if !effectiveArguments.isEmpty {
            appendWineLogLine("Arguments: \(effectiveArguments.joined(separator: " "))")
        }
        appendWineLogLine("---- process output ----")

        currentTask = Task { [weak self] in
            guard let self else { return }
            defer {
                self.isBusy = false
                self.isPaused = false
                self.isLaunchingWithWine = false
                self.currentTask = nil
                self.operationController = nil
            }
            do {
                let result = try await self.coordinator.launchGame(game, settings: self.settings) { [weak self] chunk in
                    Task { @MainActor [weak self] in
                        self?.appendWineLogChunk(chunk)
                    }
                }
                self.appendWineLogLine("---- process exited with code \(result.exitCode) ----")
                self.statusText = self.text.gameExitedNormally
                self.operationProgress = OperationProgress(
                    stageTitle: self.text.launchTitle,
                    itemPath: game.executableRelativePath,
                    partText: nil,
                    detailText: self.text.gameExitedNormally,
                    fractionCompleted: 1,
                    isIndeterminate: false,
                    currentPartDetailText: nil,
                    currentPartFractionCompleted: nil,
                    currentPartIsIndeterminate: false,
                    speedText: nil,
                    totalKBText: nil,
                    currentPartKBText: nil
                )
            } catch {
                if error is CancellationError {
                    self.appendWineLogLine("---- launch stopped by user ----")
                    self.statusText = self.text.operationStopped
                } else {
                    self.appendWineLogLine("---- launch failed ----")
                    self.appendWineLogLine(self.localizedErrorMessage(for: error))
                    self.errorMessage = self.localizedErrorMessage(for: error)
                    self.statusText = self.text.launchFailed
                }
                self.operationProgress = nil
            }
        }
    }

    /// Pauses, resumes, or restarts a resumable download depending on current state.
    func togglePause() {
        if isPaused, currentTask == nil, let game = selectedGame, resumableDownloadGameID == game.id {
            installSelectedGame()
            statusText = text.operationResumed
            return
        }

        guard isBusy, let operationController else { return }
        let newPausedValue = !isPaused
        isPaused = newPausedValue
        Task {
            if newPausedValue {
                await operationController.pause()
            } else {
                await operationController.resume()
            }
        }
        statusText = newPausedValue ? text.operationPaused : text.operationResumed
        if isUpdatingGame {
            appendUpdateLogLine(newPausedValue
                ? logText(en: "Pause requested", vi: "Đã yêu cầu tạm dừng")
                : logText(en: "Resume requested", vi: "Đã yêu cầu tiếp tục")
            )
        }
    }

    /// Stops the active operation and clears resumable state when needed.
    func stopCurrentOperation() {
        guard isBusy else { return }
        resetTransferMetricsDisplay()
        if currentTask == nil, let gameID = resumableDownloadGameID {
            // No task means the operation is paused between runs; clear the persisted resume record.
            do {
                try coordinator.clearPersistedDownloadState(for: gameID)
            } catch {
                errorMessage = localizedErrorMessage(for: error)
            }
            resumableDownloadGameID = nil
            isBusy = false
            isPaused = false
            statusText = text.operationStopped
            operationProgress = nil
            return
        }

        Task {
            await operationController?.stop()
        }
        if isLaunchingWithWine {
            appendWineLogLine("---- stop requested ----")
        }
        if isUpdatingGame {
            appendUpdateLogLine(logText(en: "---- stop requested ----", vi: "---- đã yêu cầu dừng ----"))
        }
        currentTask?.cancel()
        statusText = text.operationStopped
        isPaused = false
        resumableDownloadGameID = nil
        operationProgress = nil
    }

    /// Appends one complete line to the Wine run log.
    private func appendWineLogLine(_ line: String) {
        appendWineLogText(line + "\n")
    }

    /// Appends a streamed process chunk to the Wine run log.
    private func appendWineLogChunk(_ chunk: ProcessOutputChunk) {
        let prefix = chunk.stream == .stderr ? "[stderr] " : "[stdout] "
        let filteredLines = chunk.text
            .split(separator: "\n", omittingEmptySubsequences: false)
            .compactMap { filteredWineLogLine(String($0), prefix: prefix) }
        guard !filteredLines.isEmpty else { return }
        let normalized = filteredLines.joined(separator: "\n")
        appendWineLogText(normalized.hasSuffix("\n") ? normalized : normalized + "\n")
    }

    /// Removes large backend capability dumps while preserving actionable Wine/game diagnostics.
    private func filteredWineLogLine(_ line: String, prefix: String) -> String? {
        let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return "" }

        if trimmed.contains("[mvk-info] MoltenVK version") {
            isSkippingMoltenVKExtensionDump = true
            if didSummarizeMoltenVKDump {
                return nil
            }
            didSummarizeMoltenVKDump = true
            return "\(prefix)[mvk-info] MoltenVK initialized; verbose Vulkan capability dump hidden"
        }

        if isSkippingMoltenVKExtensionDump {
            if trimmed.hasPrefix("The following") || trimmed.hasPrefix("VK_") || trimmed.hasPrefix("[mvk-info] GPU device:") {
                return nil
            }
            isSkippingMoltenVKExtensionDump = false
        }

        if Self.isLowSignalWineLogLine(trimmed) {
            return nil
        }

        return prefix + line
    }

    /// Identifies repetitive graphics capability lines that hide the useful launch failure.
    private static func isLowSignalWineLogLine(_ trimmedLine: String) -> Bool {
        trimmedLine.hasPrefix("GPU Family ")
            || trimmedLine.hasPrefix("model:")
            || trimmedLine.hasPrefix("type:")
            || trimmedLine.hasPrefix("VK_")
            || trimmedLine.hasPrefix("[mvk-info] GPU device:")
            || trimmedLine.hasPrefix("[mvk-info] Created VkInstance")
            || trimmedLine.hasPrefix("Read-Write Texture Tier")
            || trimmedLine.hasPrefix("supports the following GPU Features")
            || trimmedLine.hasPrefix("Metal Shading Language")
            || trimmedLine.hasPrefix("pipelineCacheUUID:")
            || trimmedLine.hasPrefix("GPU memory available:")
            || trimmedLine.hasPrefix("GPU memory used:")
            || trimmedLine.hasPrefix("vendorID:")
            || trimmedLine.hasPrefix("deviceID:")
            || trimmedLine.contains("handle_DeviceMatchingCallback Ignoring HID device")
            || trimmedLine.contains("kerberos_LsaApInitializePackage no Kerberos support")
            || trimmedLine.contains("ntlm_check_version ntlm_auth was not found")
            || trimmedLine.contains("ntlm_LsaApInitializePackage no NTLM support")
            || trimmedLine.contains("wineserver: using server-side synchronization")
    }

    /// Keeps the latest Wine diagnostics bounded so the SwiftUI text view remains responsive.
    private func appendWineLogText(_ text: String) {
        wineRunLog += text
        let maxCharacters = 80_000
        if wineRunLog.count > maxCharacters {
            wineRunLog = String(wineRunLog.suffix(maxCharacters))
        }
    }

    /// Appends one complete line to the update log.
    private func appendUpdateLogLine(_ line: String) {
        appendUpdateLogText(line + "\n")
    }

    /// Appends a bounded diagnostic chunk to the update log.
    private func appendUpdateLogText(_ text: String) {
        updateRunLog += text
        let maxCharacters = 80_000
        if updateRunLog.count > maxCharacters {
            updateRunLog = String(updateRunLog.suffix(maxCharacters))
        }
    }

    /// Localizes compact diagnostic log labels without making AppText carry implementation details.
    private func logText(en: String, vi: String) -> String {
        switch settings.language {
        case .english:
            return en
        case .vietnamese:
            return vi
        }
    }

    /// Writes a bounded sample of planned update items so huge manifests remain readable.
    private func appendPlannedUpdateItemsToLog(_ plan: GameUpdatePlan) {
        switch plan.sourceKind {
        case .manifest:
            let files = plan.filesToDownload
            guard !files.isEmpty else { return }
            appendUpdateLogLine(logText(en: "Changed file sample:", vi: "Một số file sẽ cập nhật:"))
            for file in files.prefix(25) {
                let sizeText = ByteCountFormatter.string(fromByteCount: file.size, countStyle: .file)
                let checksum = file.md5?.isEmpty == false ? " md5=\(file.md5!)" : ""
                appendUpdateLogLine("- \(file.path) (\(sizeText))\(checksum)")
            }
            if files.count > 25 {
                appendUpdateLogLine(logText(en: "- ... \(files.count - 25) more files", vi: "- ... còn \(files.count - 25) file nữa"))
            }
        case .sophon:
            let assets = plan.sophonAssetsToWrite
            guard !assets.isEmpty else { return }
            appendUpdateLogLine(logText(en: "Changed Sophon asset sample:", vi: "Một số asset Sophon sẽ cập nhật:"))
            for asset in assets.prefix(25) {
                let downloadText = ByteCountFormatter.string(fromByteCount: asset.compressedBytes, countStyle: .file)
                let writeText = ByteCountFormatter.string(fromByteCount: asset.size, countStyle: .file)
                appendUpdateLogLine("- \(asset.path) (\(downloadText) download, \(writeText) write) md5=\(asset.md5)")
            }
            if assets.count > 25 {
                appendUpdateLogLine(logText(en: "- ... \(assets.count - 25) more assets", vi: "- ... còn \(assets.count - 25) asset nữa"))
            }
        }
    }

    /// Records manifest update progress at useful milestones without flooding the UI.
    private func appendUpdateProgressLog(path: String, overallReceived: Int64, overallTotal: Int64, fileReceived: Int64, fileTotal: Int64) {
        guard isUpdatingGame else { return }

        if fileReceived == 0 {
            appendUpdateLogLine(logText(
                en: "[download] start \(path) (\(ByteCountFormatter.string(fromByteCount: fileTotal, countStyle: .file)))",
                vi: "[download] bắt đầu \(path) (\(ByteCountFormatter.string(fromByteCount: fileTotal, countStyle: .file)))"
            ))
            return
        }

        if fileTotal > 0, fileReceived >= fileTotal, !updateLoggedCompletedFiles.contains(path) {
            updateLoggedCompletedFiles.insert(path)
            appendUpdateLogLine(logText(en: "[download] completed \(path)", vi: "[download] xong \(path)"))
            return
        }

        guard overallTotal > 0 else { return }
        let bucket = Int((Double(overallReceived) / Double(overallTotal) * 100).rounded(.down) / 5) * 5
        guard bucket > 0, bucket < 100, bucket != lastUpdateLogOverallBucket else { return }
        lastUpdateLogOverallBucket = bucket
        let receivedText = ByteCountFormatter.string(fromByteCount: overallReceived, countStyle: .file)
        let totalText = ByteCountFormatter.string(fromByteCount: overallTotal, countStyle: .file)
        appendUpdateLogLine(logText(en: "[progress] \(bucket)% (\(receivedText) / \(totalText))", vi: "[tiến độ] \(bucket)% (\(receivedText) / \(totalText))"))
    }

    /// Maps service-layer progress events into stable UI state.
    private func apply(event: InstallProgressEvent) {
        switch event {
        case let .preparing(path):
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "[prepare] \(path)", vi: "[chuẩn bị] \(path)"))
            }
            statusText = text.preparing(path)
            operationProgress = OperationProgress(
                stageTitle: text.preparingStage,
                itemPath: path,
                partText: nil,
                detailText: nil,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .readyToExtract(downloadedParts, totalParts):
            let detail = text.extractionStartsAfterDownload(downloadedParts: downloadedParts, totalParts: totalParts)
            statusText = detail
            operationProgress = OperationProgress(
                stageTitle: text.preparingStage,
                itemPath: nil,
                partText: text.partProgress(current: downloadedParts, total: totalParts),
                detailText: detail,
                resumePointText: nil,
                fractionCompleted: 1,
                isIndeterminate: false,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: false,
                speedText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .downloadingPackage(path, received, total, currentPart, totalParts, currentPartReceived, currentPartTotal, _):
            let receivedText = ByteCountFormatter.string(fromByteCount: received, countStyle: .file)
            let totalText = ByteCountFormatter.string(fromByteCount: total, countStyle: .file)
            let currentPartReceivedText = ByteCountFormatter.string(fromByteCount: currentPartReceived ?? 0, countStyle: .file)
            let currentPartTotalText = ByteCountFormatter.string(fromByteCount: currentPartTotal ?? 0, countStyle: .file)
            let derivedMetrics = deriveTransferMetrics(received: received, total: total)
            let latestSpeedText = derivedMetrics.speedBytesPerSecond.map {
                ByteCountFormatter.string(fromByteCount: $0, countStyle: .file) + "/s"
            }
            let latestEtaText: String? = {
                guard derivedMetrics.isWarmupComplete,
                      let speedBytesPerSecond = derivedMetrics.speedBytesPerSecond,
                      speedBytesPerSecond > 0,
                      total > received else { return nil }
                return formatETA(seconds: Double(total - received) / Double(speedBytesPerSecond))
            }()
            let transferMetrics = throttledTransferMetrics(
                latestSpeedText: latestSpeedText,
                latestEtaText: latestEtaText
            )
            let partLabel: String? = {
                if let currentPart, let totalParts {
                    return text.partProgress(current: currentPart, total: totalParts)
                }
                return nil
            }()
            let latestDetailText = received == 0
                ? text.waitingForFirstDownloadBytes
                : text.progressValue(received: receivedText, total: totalText)
            let latestCurrentPartDetailText = (currentPartReceived ?? 0) == 0
                ? text.waitingForFirstDownloadBytes
                : text.currentPartProgressValue(received: currentPartReceivedText, total: currentPartTotalText)
            let latestTotalKBText = text.progressValueKB(
                receivedKB: String(received / 1024),
                totalKB: String(total / 1024)
            )
            let latestCurrentPartKBText: String? = {
                guard let currentPartReceived, let currentPartTotal else { return nil }
                return text.progressValueKB(
                    receivedKB: String(currentPartReceived / 1024),
                    totalKB: String(currentPartTotal / 1024)
                )
            }()
            let throttledFields = throttledDownloadFields(
                path: path,
                partText: partLabel,
                latestDetailText: latestDetailText,
                latestCurrentPartDetailText: latestCurrentPartDetailText,
                latestTotalKBText: latestTotalKBText,
                latestCurrentPartKBText: latestCurrentPartKBText
            )
            statusText = text.downloadingPackage(
                path,
                received: receivedText,
                total: totalText
            )
            operationProgress = OperationProgress(
                stageTitle: text.downloadingStage,
                itemPath: path,
                partText: throttledFields.partText,
                detailText: throttledFields.detailText,
                resumePointText: received > 0 ? text.resumePointValue(receivedText) : nil,
                fractionCompleted: total > 0 ? min(max(Double(received) / Double(total), 0), 1) : nil,
                isIndeterminate: total <= 0 || received == 0,
                currentPartDetailText: throttledFields.currentPartDetailText,
                currentPartFractionCompleted: {
                    guard let currentPartReceived, let currentPartTotal, currentPartTotal > 0 else { return nil }
                    return min(max(Double(currentPartReceived) / Double(currentPartTotal), 0), 1)
                }(),
                currentPartIsIndeterminate: (currentPartTotal ?? 0) <= 0 || (currentPartReceived ?? 0) == 0,
                speedText: transferMetrics.speedText,
                etaText: transferMetrics.etaText,
                isETAWarmingUp: !derivedMetrics.isWarmupComplete && received > 0,
                totalKBText: throttledFields.totalKBText,
                currentPartKBText: throttledFields.currentPartKBText
            )
        case let .downloading(path, received, total):
            let receivedText = ByteCountFormatter.string(fromByteCount: received, countStyle: .file)
            let totalText = ByteCountFormatter.string(fromByteCount: total, countStyle: .file)
            statusText = text.downloaded(
                path,
                received: receivedText,
                total: totalText
            )
            operationProgress = OperationProgress(
                stageTitle: text.downloadingStage,
                itemPath: path,
                partText: nil,
                detailText: text.progressValue(received: receivedText, total: totalText),
                fractionCompleted: total > 0 ? min(max(Double(received) / Double(total), 0), 1) : nil,
                isIndeterminate: total <= 0,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                etaText: nil,
                totalKBText: text.progressValueKB(
                    receivedKB: String(received / 1024),
                    totalKB: String(total / 1024)
                ),
                currentPartKBText: nil
            )
        case let .downloadingManifest(path, overallReceived, overallTotal, fileReceived, fileTotal):
            appendUpdateProgressLog(
                path: path,
                overallReceived: overallReceived,
                overallTotal: overallTotal,
                fileReceived: fileReceived,
                fileTotal: fileTotal
            )
            let overallReceivedText = ByteCountFormatter.string(fromByteCount: overallReceived, countStyle: .file)
            let overallTotalText = ByteCountFormatter.string(fromByteCount: overallTotal, countStyle: .file)
            let fileReceivedText = ByteCountFormatter.string(fromByteCount: fileReceived, countStyle: .file)
            let fileTotalText = ByteCountFormatter.string(fromByteCount: fileTotal, countStyle: .file)
            let overallFraction = overallTotal > 0 ? min(max(Double(overallReceived) / Double(overallTotal), 0), 1) : nil
            let fileFraction = fileTotal > 0 ? min(max(Double(fileReceived) / Double(fileTotal), 0), 1) : nil
            let derivedMetrics = deriveTransferMetrics(received: overallReceived, total: overallTotal)
            let latestSpeedText = derivedMetrics.speedBytesPerSecond.map {
                ByteCountFormatter.string(fromByteCount: $0, countStyle: .file) + "/s"
            }
            let latestEtaText: String? = {
                guard derivedMetrics.isWarmupComplete,
                      let speedBytesPerSecond = derivedMetrics.speedBytesPerSecond,
                      speedBytesPerSecond > 0,
                      overallTotal > overallReceived else { return nil }
                return formatETA(seconds: Double(overallTotal - overallReceived) / Double(speedBytesPerSecond))
            }()
            let transferMetrics = throttledTransferMetrics(
                latestSpeedText: latestSpeedText,
                latestEtaText: latestEtaText
            )
            let latestDetailText = progressDetailText(
                receivedText: overallReceivedText,
                totalText: overallTotalText,
                fraction: overallFraction
            )
            let latestCurrentPartDetailText = progressDetailText(
                receivedText: fileReceivedText,
                totalText: fileTotalText,
                fraction: fileFraction
            )
            let latestTotalKBText = text.progressValueKB(
                receivedKB: String(overallReceived / 1024),
                totalKB: String(overallTotal / 1024)
            )
            let latestCurrentPartKBText = text.progressValueKB(
                receivedKB: String(fileReceived / 1024),
                totalKB: String(fileTotal / 1024)
            )
            let throttledFields = throttledDownloadFields(
                path: path,
                partText: nil,
                latestDetailText: latestDetailText,
                latestCurrentPartDetailText: latestCurrentPartDetailText,
                latestTotalKBText: latestTotalKBText,
                latestCurrentPartKBText: latestCurrentPartKBText
            )
            let activeItems = registerActiveManifestItem(path)
            statusText = text.downloadingPackage(
                path,
                received: overallReceivedText,
                total: overallTotalText
            )
            operationProgress = OperationProgress(
                stageTitle: text.downloadingStage,
                itemPath: path,
                itemPaths: activeItems,
                partText: nil,
                detailText: throttledFields.detailText,
                fractionCompleted: overallFraction,
                isIndeterminate: overallTotal <= 0,
                currentPartDetailText: throttledFields.currentPartDetailText,
                currentPartFractionCompleted: fileFraction,
                currentPartIsIndeterminate: fileTotal <= 0,
                speedText: transferMetrics.speedText,
                etaText: transferMetrics.etaText,
                isETAWarmingUp: !derivedMetrics.isWarmupComplete && overallReceived > 0,
                totalKBText: throttledFields.totalKBText,
                currentPartKBText: throttledFields.currentPartKBText
            )
        case let .extracting(path):
            statusText = text.extracting(path)
            operationProgress = OperationProgress(
                stageTitle: text.extractingStage,
                itemPath: path,
                partText: nil,
                detailText: nil,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .verifying(path):
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "[verify] \(path)", vi: "[xác thực] \(path)"))
            }
            statusText = text.verifying(path)
            operationProgress = OperationProgress(
                stageTitle: text.verifyingStage,
                itemPath: path,
                partText: nil,
                detailText: nil,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .validatingInstall(path):
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "[validate] \(path)", vi: "[kiểm tra] \(path)"))
            }
            statusText = text.validating(path)
            operationProgress = OperationProgress(
                stageTitle: text.validatingStage,
                itemPath: path,
                partText: nil,
                detailText: nil,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .cleaningDownloadedArchives(path):
            let detail = text.cleaningDownloadedArchives(path)
            statusText = detail
            operationProgress = OperationProgress(
                stageTitle: text.cleaningStage,
                itemPath: path,
                partText: nil,
                detailText: text.downloadedArchivesCleanedUp,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .importing(path):
            statusText = text.importingPath(path)
            operationProgress = OperationProgress(
                stageTitle: text.importingStage,
                itemPath: path,
                partText: nil,
                detailText: nil,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .finished(version):
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "[metadata] wrote version \(version)", vi: "[metadata] đã ghi bản \(version)"))
            }
            statusText = text.installedVersion(version)
            operationProgress = OperationProgress(
                stageTitle: text.completedStage,
                itemPath: version,
                partText: nil,
                detailText: text.installedVersion(version),
                fractionCompleted: 1,
                isIndeterminate: false,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: false,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        }
    }

    /// Formats ETA with coarse rounding so the UI does not flicker every second.
    private func formatETA(seconds: Double) -> String? {
        guard seconds.isFinite, seconds > 0 else { return nil }
        let roundedSeconds: Double
        switch seconds {
        case 0..<60:
            roundedSeconds = (seconds / 5).rounded() * 5
        case 60..<600:
            roundedSeconds = (seconds / 15).rounded() * 15
        case 600..<3600:
            roundedSeconds = (seconds / 30).rounded() * 30
        default:
            roundedSeconds = (seconds / 60).rounded() * 60
        }
        let formatter = DateComponentsFormatter()
        formatter.allowedUnits = roundedSeconds >= 3600 ? [.hour, .minute] : [.minute, .second]
        formatter.unitsStyle = .full
        formatter.maximumUnitCount = 2
        return formatter.string(from: roundedSeconds)
    }

    /// Throttles speed and ETA labels independently from raw download callbacks.
    private func throttledTransferMetrics(latestSpeedText: String?, latestEtaText: String?) -> (speedText: String?, etaText: String?) {
        let now = Date()
        let shouldRefresh = {
            guard let lastTransferMetricsUpdateAt else { return true }
            return now.timeIntervalSince(lastTransferMetricsUpdateAt) >= 1.5
        }()

        if shouldRefresh || displayedSpeedText == nil || displayedEtaText == nil {
            displayedSpeedText = latestSpeedText
            displayedEtaText = latestEtaText
            lastTransferMetricsUpdateAt = now
        } else if latestSpeedText == nil {
            displayedSpeedText = nil
        }

        if latestEtaText == nil {
            displayedEtaText = nil
        }

        return (displayedSpeedText, displayedEtaText)
    }

    /// Formats byte progress with a percent suffix when the total is known.
    private func progressDetailText(receivedText: String, totalText: String, fraction: Double?) -> String {
        let byteText = text.progressValue(received: receivedText, total: totalText)
        guard let fraction else { return byteText }
        let percent = NumberFormatter.localizedString(
            from: NSNumber(value: min(max(fraction, 0), 1)),
            number: .percent
        )
        return "\(byteText) (\(percent))"
    }

    /// Clears cached transfer metrics when starting a new operation.
    private func resetTransferMetricsDisplay() {
        lastTransferMetricsUpdateAt = nil
        displayedSpeedText = nil
        displayedEtaText = nil
        transferSamples = []
        lastDownloadFieldsUpdateAt = nil
        displayedDownloadFields = nil
    }

    /// Throttles high-frequency download text fields to keep SwiftUI updates smooth.
    private func throttledDownloadFields(
        path: String,
        partText: String?,
        latestDetailText: String,
        latestCurrentPartDetailText: String?,
        latestTotalKBText: String?,
        latestCurrentPartKBText: String?
    ) -> DownloadFieldSnapshot {
        let now = Date()
        let latest = DownloadFieldSnapshot(
            path: path,
            partText: partText,
            detailText: latestDetailText,
            currentPartDetailText: latestCurrentPartDetailText,
            totalKBText: latestTotalKBText,
            currentPartKBText: latestCurrentPartKBText
        )

        let shouldRefresh = {
            guard let displayedDownloadFields else { return true }
            guard let lastDownloadFieldsUpdateAt else { return true }
            if displayedDownloadFields.path != latest.path || displayedDownloadFields.partText != latest.partText {
                return true
            }
            return now.timeIntervalSince(lastDownloadFieldsUpdateAt) >= 0.8
        }()

        if shouldRefresh {
            displayedDownloadFields = latest
            lastDownloadFieldsUpdateAt = now
        }

        return displayedDownloadFields ?? latest
    }

    /// Computes rolling transfer speed and ETA readiness from recent samples.
    private func deriveTransferMetrics(received: Int64, total: Int64) -> (speedBytesPerSecond: Int64?, etaSeconds: Double?, isWarmupComplete: Bool) {
        let now = Date()
        // Keep samples dense enough for responsiveness but sparse enough to avoid noisy speed estimates.
        let minimumSampleSpacing: TimeInterval = 0.5
        let rollingWindow: TimeInterval = 12
        let etaWarmupDuration: TimeInterval = 5

        if let lastSample = transferSamples.last {
            let deltaTime = now.timeIntervalSince(lastSample.date)
            let deltaBytes = received - lastSample.receivedBytes
            if deltaTime >= minimumSampleSpacing || deltaBytes >= 512 * 1024 || deltaBytes < 0 {
                transferSamples.append(TransferSample(date: now, receivedBytes: received))
            } else {
                transferSamples[transferSamples.count - 1] = TransferSample(date: now, receivedBytes: received)
            }
        } else {
            transferSamples.append(TransferSample(date: now, receivedBytes: received))
        }

        transferSamples.removeAll { now.timeIntervalSince($0.date) > rollingWindow }

        guard let first = transferSamples.first, let last = transferSamples.last else {
            return (nil, nil, false)
        }

        let elapsed = last.date.timeIntervalSince(first.date)
        let transferredBytes = last.receivedBytes - first.receivedBytes
        guard elapsed >= 1, transferredBytes > 0 else {
            return (nil, nil, false)
        }

        let speed = Int64((Double(transferredBytes) / elapsed).rounded())
        let eta: Double? = {
            guard speed > 0, total > received else { return nil }
            return Double(total - received) / Double(speed)
        }()
        return (speed, eta, elapsed >= etaWarmupDuration)
    }

    /// Mutates the selected game in settings.
    private func updateSelectedGame(_ update: (inout GameDefinition) -> Void) {
        guard !settings.games.isEmpty else { return }
        update(&settings.games[0])
    }

    /// Restores paused download state on startup when a checkpoint exists.
    private func restorePersistedDownloadStateIfNeeded() {
        guard currentTask == nil, let game = selectedGame else { return }

        guard let state = try? coordinator.loadPersistedDownloadState(for: game.id) else {
            if resumableDownloadGameID == game.id {
                resumableDownloadGameID = nil
                isBusy = false
                isPaused = false
                operationProgress = nil
                statusText = text.ready
            }
            return
        }

        applyPersistedDownloadState(state, for: game.id)
    }

    /// Shows a paused download as resumable progress in the UI.
    private func applyPersistedDownloadState(_ state: PersistedDownloadState, for gameID: String) {
        resumableDownloadGameID = gameID
        isBusy = true
        isPaused = true

        let totalBytes = state.totalExpectedBytes ?? max(state.downloadedBytes, 0)
        let receivedText = ByteCountFormatter.string(fromByteCount: state.downloadedBytes, countStyle: .file)
        let totalText = ByteCountFormatter.string(fromByteCount: totalBytes, countStyle: .file)
        let currentPartReceivedText = ByteCountFormatter.string(fromByteCount: state.currentPartReceivedBytes, countStyle: .file)
        let currentPartTotalText = ByteCountFormatter.string(fromByteCount: state.currentPartExpectedBytes ?? 0, countStyle: .file)

        statusText = text.pausedDownloadReadyToResume
        operationProgress = OperationProgress(
            stageTitle: text.downloadingStage,
            itemPath: state.currentPartFileName,
            partText: {
                guard let currentPart = state.currentPart, let totalParts = state.totalParts else { return nil }
                return text.partProgress(current: currentPart, total: totalParts)
            }(),
            detailText: text.progressValue(received: receivedText, total: totalText),
            resumePointText: text.resumePointValue(receivedText),
            fractionCompleted: totalBytes > 0 ? min(max(Double(state.downloadedBytes) / Double(totalBytes), 0), 1) : nil,
            isIndeterminate: totalBytes <= 0,
            currentPartDetailText: state.currentPartExpectedBytes.map { _ in
                text.currentPartProgressValue(received: currentPartReceivedText, total: currentPartTotalText)
            },
            currentPartFractionCompleted: {
                guard let currentPartExpectedBytes = state.currentPartExpectedBytes, currentPartExpectedBytes > 0 else { return nil }
                return min(max(Double(state.currentPartReceivedBytes) / Double(currentPartExpectedBytes), 0), 1)
            }(),
            currentPartIsIndeterminate: (state.currentPartExpectedBytes ?? 0) <= 0,
            speedText: nil,
            etaText: nil,
            totalKBText: text.progressValueKB(
                receivedKB: String(state.downloadedBytes / 1024),
                totalKB: String(totalBytes / 1024)
            ),
            currentPartKBText: state.currentPartExpectedBytes.map {
                text.progressValueKB(
                    receivedKB: String(state.currentPartReceivedBytes / 1024),
                    totalKB: String($0 / 1024)
                )
            }
        )
    }

    /// Converts domain errors into localized UI strings.
    private func localizedErrorMessage(for error: Error) -> String {
        switch error {
        case let wineError as WineServiceError:
            switch wineError {
            case let .binaryQuarantined(path):
                return text.wineBinaryQuarantined(path)
            case let .dxvkBootstrapFailed(details):
                return text.dxvkBootstrapFailed(details)
            case let .dxmtBootstrapFailed(details):
                return text.dxmtBootstrapFailed(details)
            case let .dxmtUnsupportedWine(path):
                return text.dxmtUnsupportedWine(path)
            }
        case let processError as ProcessRunnerError:
            switch processError {
            case let .executableNotFound(path):
                return text.executableNotFound(path)
            case let .nonZeroExit(result):
                let details = result.stderr.isEmpty ? result.stdout : result.stderr
                return text.processFailed(code: result.exitCode, details: details)
            }
        case let downloadError as PackageDownloadError:
            switch downloadError {
            case .packageSourceMissing:
                return text.packageSourceMissing
            case .remoteURLMissing:
                return text.packageRemoteURLMissing
            case .invalidResponse:
                return text.packageServerInvalidResponse
            case let .downloadedPartIntegrityMismatch(fileName, expectedBytes, actualBytes):
                return text.downloadedPartIntegrityMismatch(
                    fileName,
                    expected: ByteCountFormatter.string(fromByteCount: expectedBytes, countStyle: .file),
                    actual: ByteCountFormatter.string(fromByteCount: actualBytes, countStyle: .file)
                )
            }
        case let archiveError as ArchiveInstallerError:
            switch archiveError {
            case .packageSourceMissing:
                return text.archivePackageMissing
            case .sevenZipBinaryMissing:
                return text.sevenZipBinaryMissing
            case let .sevenZipBinaryNotFound(path):
                return text.sevenZipBinaryNotFound(path)
            case let .expectedExecutableMissing(path):
                return text.expectedExecutableMissingAfterExtraction(path)
            }
        case let manifestError as ManifestInstallerError:
            switch manifestError {
            case .manifestURLMissing:
                return text.manifestURLMissing
            case .invalidResponse:
                return text.serverInvalidResponse
            case let .checksumMismatch(path):
                return text.checksumMismatch(path)
            case let .expectedExecutableMissing(path):
                return text.missingExpectedExecutable(path)
            }
        case let streamingError as GenshinStreamingMetadataError:
            switch streamingError {
            case .officialStreamingMetadataUnavailable:
                return text.officialStreamingMetadataUnavailable
            case .streamingManifestIncomplete:
                return text.streamingManifestIncomplete
            case .freshInstallUnsupported:
                return text.freshInstallUnsupported
            case let .packageManifestStale(currentVersion, evidence):
                return text.packageManifestStale(currentVersion: currentVersion, evidence: evidence)
            case let .sophonUpdateRequired(currentVersion, latestVersion, evidence):
                return text.sophonUpdateRequired(
                    currentVersion: currentVersion,
                    latestVersion: latestVersion,
                    evidence: evidence
                )
            }
        case let sophonError as SophonInstallerError:
            switch sophonError {
            case .zstdUnavailable:
                return text.sophonZstdUnavailable
            default:
                return text.sophonUpdateFailed(sophonError.localizedDescription)
            }
        case let importError as ImportServiceError:
            switch importError {
            case let .expectedExecutableMissing(path):
                return text.missingExpectedExecutable(path)
            }
        case is CancellationError:
            return text.operationStopped
        default:
            return error.localizedDescription
        }
    }

    /// Tracks recently active manifest files for the multi-file progress list.
    private func registerActiveManifestItem(_ path: String) -> [String] {
        let now = Date()
        activeManifestItems[path] = now
        activeManifestItems = activeManifestItems.filter { now.timeIntervalSince($0.value) < 2.5 }
        return activeManifestItems
            .sorted { $0.value > $1.value }
            .map(\.key)
            .prefix(16)
            .map { $0 }
    }

    /// Clears the manifest activity list between operations.
    private func resetActiveManifestItems() {
        activeManifestItems.removeAll()
    }
}

/// One transfer sample used for rolling speed and ETA calculations.
private struct TransferSample {
    let date: Date
    let receivedBytes: Int64
}

/// Cached download text fields used to reduce UI refresh churn.
private struct DownloadFieldSnapshot {
    let path: String
    let partText: String?
    let detailText: String
    let currentPartDetailText: String?
    let totalKBText: String?
    let currentPartKBText: String?
}
