// LauncherViewModel.swift
//
// Main UI state machine. Owns published settings/status/progress/log state, starts
// install/update/launch tasks, and maps service events into stable SwiftUI state.
//
// Responsibilities:
// - bootstrap the production dependency graph and load/migrate settings;
// - plan/install/update via LauncherCoordinator, with pause/stop/transfer metrics;
// - voice-pack management (refresh + remove, blocking removal of the selected pack);
// - Wine launch with filtered, bounded logging;
// - localized error mapping for every service error type.
//
// Logs are capped (~80k chars) so the SwiftUI text views stay responsive; progress
// and speed/ETA are throttled independently of the raw download callbacks.

import Foundation
import SwiftUI

/// UI-facing snapshot of the currently running launcher operation.
struct OperationProgress: Equatable {
    var stageTitle: String
    var itemPath: String?
    var itemPaths: [String]? = nil
    var partText: String?
    var detailText: String?
    var resumePointText: String? = nil
    var fractionCompleted: Double?
    var isIndeterminate: Bool
    var currentPartDetailText: String?
    var currentPartFractionCompleted: Double?
    var currentPartIsIndeterminate: Bool
    var speedText: String?
    var etaText: String?
    var isETAWarmingUp: Bool = false
    var totalKBText: String?
    var currentPartKBText: String?
}

/// Main application view model that connects SwiftUI state to launcher services.
@MainActor
final class LauncherViewModel: ObservableObject {
    /// Persisted user configuration currently displayed by the UI.
    @Published var settings: AppSettings
    /// Primary status line shown in the main window.
    @Published var statusText: String
    /// Last human-readable plan summary generated by the planner.
    @Published var lastPlanSummary = ""
    /// True while an install or launch task is active.
    @Published var isBusy = false
    /// Localized error message displayed in the alert.
    @Published var errorMessage: String?
    /// Structured progress displayed by the status panel.
    @Published var operationProgress: OperationProgress?
    /// True when a running or resumable operation is paused.
    @Published var isPaused = false
    /// True while the selected game is being launched through Wine.
    @Published var isLaunchingWithWine = false
    /// Streaming diagnostic log for the latest Wine launch.
    @Published var wineRunLog = ""
    /// Streaming diagnostic log for the latest game update.
    @Published var updateRunLog = ""
    /// Bumped on every published log change so views can drive auto-scroll without measuring the
    /// log text itself; `contents.count` is O(n) and the panel re-renders far more often than the
    /// log changes.
    @Published var runLogVersion = 0
    /// True while the selected game is being updated through Sophon.
    @Published var isUpdatingGame = false
    /// Voice-over packages with local assets in the selected game installation.
    @Published var voicePackages: [VoicePackage] = []
    /// Audio storage derived from the selected game's local files and live manifest.
    @Published var storageInventory = GameStorageInventory.empty
    /// True while voice packages are being refreshed or removed.
    @Published var isManagingVoicePacks = false
    /// Removable cache categories with their current on-disk sizes.
    @Published var cacheReport: [RemovableCache] = []
    /// True while cache sizes are being refreshed or a category is being cleared.
    @Published var isManagingCache = false
    /// True while CrossOver is being installed through Homebrew.
    @Published var isInstallingCrossOver = false

    private let coordinator: LauncherCoordinator
    private var currentTask: Task<Void, Never>?
    private var operationController: OperationController?
    private var transferRate = TransferRateEstimator()
    private var transferMetricsThrottle = TransferMetricsThrottle()
    private var downloadFieldThrottle = DownloadFieldThrottle()
    private var activeSophonItems: [String: Date] = [:]
    private var lastUpdateLogOverallBucket: Int?
    private var updateLoggedCompletedFiles: Set<String> = []
    private var wineLogFilter = WineLogFilter()
    private var wineLogBuffer = RunLogBuffer()
    private var updateLogBuffer = RunLogBuffer()
    private var runLogFlushTask: Task<Void, Never>?

    /// How long buffered log text waits before it is published. Long enough to collapse a burst of
    /// process output, short enough that the panel still reads as live.
    private static let runLogFlushInterval: UInt64 = 250_000_000

    /// Creates a view model with already-loaded settings and a configured coordinator.
    init(settings: AppSettings, coordinator: LauncherCoordinator) {
        self.settings = settings
        self.statusText = AppText(language: settings.language).ready
        self.coordinator = coordinator
    }

    /// Builds the production dependency graph and loads settings for app startup.
    static func bootstrap() -> LauncherViewModel {
        let processRunner = ProcessRunner()
        let coordinator = LauncherCoordinator(
            settingsStore: SettingsStore(),
            sophonInstaller: GenshinSophonInstaller(),
            wineService: WineService(processRunner: processRunner),
            processRunner: processRunner
        )

        let loadedSettings = (try? coordinator.loadSettings()) ?? .default
        let settings = loadedSettings.applyingBundledGenshinDefaultsIfNeeded()
        if settings != loadedSettings {
            try? coordinator.saveSettings(settings)
        }
        return LauncherViewModel(settings: settings, coordinator: coordinator)
    }

    /// Games configured in settings.
    var games: [GameDefinition] { settings.games }

    /// Currently selected game; this app currently exposes the first configured game.
    var selectedGame: GameDefinition? {
        games.first
    }

    /// Whether the selected game has enough remote Sophon metadata to start a download.
    var canDownloadSelectedGame: Bool {
        selectedGame != nil
    }

    /// Whether the selected game can be updated from Sophon metadata.
    var canUpdateSelectedGame: Bool {
        selectedGame != nil
    }

    /// Localized text helper derived from the current setting.
    var text: AppText {
        AppText(language: settings.language)
    }

    /// Persists settings and surfaces any write error to the UI.
    func persistSettings() {
        do {
            try coordinator.saveSettings(settings)
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    /// Writes one setting and persists it.
    ///
    /// Replaces sixteen two-line methods that differed only in which field they assigned. Settings
    /// that clamp or sanitize their input keep their own method below, so the sanitizing cannot be
    /// skipped by a caller reaching for this one.
    func update<Value>(_ keyPath: WritableKeyPath<AppSettings, Value>, to value: Value) {
        settings[keyPath: keyPath] = value
        persistSettings()
    }

    /// Updates the UI language and persists the choice.
    func setLanguage(_ language: AppLanguage) {
        statusText = AppText(language: language).ready
        update(\.language, to: language)
    }

    /// Updates the custom-resolution width and persists the choice.
    func setResolutionWidth(_ width: Int) {
        update(\.resolutionWidth, to: max(width, 1))
    }

    /// Updates the custom-resolution height and persists the choice.
    func setResolutionHeight(_ height: Int) {
        update(\.resolutionHeight, to: max(height, 1))
    }

    /// Refreshes local storage inventory for the selected game.
    func refreshVoicePackages() {
        guard !isManagingVoicePacks, let game = selectedGame else { return }
        isManagingVoicePacks = true
        statusText = text.checkingStorageInventory
        errorMessage = nil

        Task { [weak self] in
            guard let self else { return }
            defer { self.isManagingVoicePacks = false }
            do {
                let inventory = try await self.coordinator.fetchStorageInventory(for: game, settings: self.settings)
                self.storageInventory = inventory
                self.voicePackages = inventory.voicePackages.sorted { $0.localBytes > $1.localBytes }
                if inventory.voicePackages.isEmpty {
                    self.statusText = self.text.noVoicePacksFound
                } else {
                    self.statusText = self.text.ready
                }
            } catch {
                self.errorMessage = self.text.message(for: error)
                self.statusText = self.text.storageInventoryFailed
            }
        }
    }

    /// Removes the local files of a voice pack. The launcher no longer downloads any voice pack
    /// itself, so every pack found on disk is leftover and safe to remove.
    func removeVoicePack(_ package: VoicePackage) {
        guard !isManagingVoicePacks else { return }
        guard let game = selectedGame else { return }

        isManagingVoicePacks = true
        statusText = text.removingVoicePack
        errorMessage = nil

        Task { [weak self] in
            guard let self else { return }
            defer { self.isManagingVoicePacks = false }
            do {
                let freedBytes = try await self.coordinator.removeVoicePack(
                    matchingField: package.matchingField,
                    game: game
                )
                self.voicePackages.removeAll { $0.matchingField == package.matchingField }
                self.storageInventory.voicePackages.removeAll { $0.matchingField == package.matchingField }
                self.statusText = self.text.voicePackRemoved(
                    ByteCountFormatter.string(fromByteCount: freedBytes, countStyle: .file)
                )
            } catch {
                self.errorMessage = self.text.message(for: error)
                self.statusText = self.text.voicePackRemoveFailed
            }
        }
    }

    /// Scans removable cache categories for the selected game off the main actor.
    func refreshCacheReport() {
        guard !isManagingCache, let game = selectedGame else { return }
        isManagingCache = true
        let coordinator = self.coordinator
        Task.detached(priority: .userInitiated) {
            let report = coordinator.fetchCacheReport(for: game)
            await MainActor.run { [weak self] in
                self?.cacheReport = report
                self?.isManagingCache = false
            }
        }
    }

    /// Clears one removable cache category off the main actor, then refreshes the report.
    func clearCache(_ kind: RemovableCache.Kind) {
        guard !isManagingCache, let game = selectedGame else { return }
        isManagingCache = true
        statusText = text.clearingCache
        errorMessage = nil
        let coordinator = self.coordinator
        Task.detached(priority: .userInitiated) {
            let outcome: Result<Int64, Error>
            do {
                outcome = .success(try coordinator.clearCache(kind, for: game))
            } catch {
                outcome = .failure(error)
            }
            let report = coordinator.fetchCacheReport(for: game)
            await MainActor.run { [weak self] in
                guard let self else { return }
                self.cacheReport = report
                switch outcome {
                case let .success(freedBytes):
                    self.statusText = self.text.cacheCleared(
                        ByteCountFormatter.string(fromByteCount: freedBytes, countStyle: .file)
                    )
                case let .failure(error):
                    self.errorMessage = self.text.message(for: error)
                    self.statusText = self.text.cacheClearFailed
                }
                self.isManagingCache = false
            }
        }
    }

    /// True once a CrossOver carrying Apple D3DMetal is installed — hides the install action in
    /// Settings once it is no longer needed.
    var isCrossOverInstalled: Bool { CrossOverInstaller.isInstalled }

    /// Installs CrossOver through Homebrew so the D3DMetal render backend has a build to select.
    ///
    /// Only ever triggered by an explicit tap in Settings — see `CrossOverInstaller` for why this
    /// installs a paid trial and must never run on its own.
    func installCrossOverViaHomebrew() {
        guard !isInstallingCrossOver else { return }
        isInstallingCrossOver = true
        errorMessage = nil
        statusText = text.installingCrossOver

        Task { [weak self] in
            guard let self else { return }
            defer { self.isInstallingCrossOver = false }
            do {
                try await self.coordinator.installCrossOverViaHomebrew { [weak self] line in
                    Task { @MainActor [weak self] in
                        self?.statusText = line
                    }
                }
                self.statusText = self.text.crossOverInstalled
            } catch {
                self.errorMessage = self.text.message(for: error)
                self.statusText = self.text.crossOverInstallFailedStatus
            }
        }
    }

    /// Updates the selected game by downloading only missing or changed Sophon assets.
    func updateSelectedGame() {
        guard let game = selectedGame, canUpdateSelectedGame else { return }
        resetTransferMetricsDisplay()
        resetActiveSophonItems()
        currentTask?.cancel()
        isBusy = true
        isPaused = false
        isUpdatingGame = true
        discardBufferedRunLogs()
        updateLogBuffer.reset()
        updateRunLog = ""
        lastUpdateLogOverallBucket = nil
        updateLoggedCompletedFiles.removeAll()
        operationController = OperationController()
        operationProgress = OperationProgress(
            stageTitle: text.updateGameTitle,
            itemPath: game.displayName,
            partText: nil,
            detailText: text.checkingForUpdates(game.displayName),
            fractionCompleted: nil,
            isIndeterminate: true,
            currentPartDetailText: nil,
            currentPartFractionCompleted: nil,
            currentPartIsIndeterminate: true,
            speedText: nil,
            etaText: nil,
            totalKBText: nil,
            currentPartKBText: nil
        )
        statusText = text.checkingForUpdates(game.displayName)
        errorMessage = nil
        appendUpdateLogLine(logText(en: "Update \(game.displayName)", vi: "Cập nhật \(game.displayName)"))
        appendUpdateLogLine(logText(en: "Install directory: \(game.installDirectory.path)", vi: "Thư mục cài đặt: \(game.installDirectory.path)"))
        appendUpdateLogLine(logText(en: "Executable: \(game.executableRelativePath)", vi: "File chạy: \(game.executableRelativePath)"))
        appendUpdateLogLine(logText(en: "Runtime requirements: \(game.runtimeRequirements.map(\.rawValue).joined(separator: ", "))", vi: "Runtime cần có: \(game.runtimeRequirements.map(\.rawValue).joined(separator: ", "))"))
        appendUpdateLogLine(logText(en: "---- check latest Sophon build ----", vi: "---- kiểm tra Sophon build mới nhất ----"))

        currentTask = Task { [weak self] in
            guard let self else { return }
            defer {
                self.isBusy = false
                self.isPaused = false
                self.isUpdatingGame = false
                self.currentTask = nil
                self.operationController = nil
                self.flushRunLogs()
            }
            do {
                let plan = try await self.coordinator.fetchUpdatePlan(
                    for: game,
                    settings: self.settings
                ) { [weak self] event in
                    await MainActor.run {
                        self?.apply(event: event)
                    }
                }
                let currentVersion = plan.installedVersion ?? self.text.missingVersionLabel
                let downloadText = ByteCountFormatter.string(fromByteCount: plan.bytesToDownload, countStyle: .file)
                let summary = self.text.updatePlanSummary(
                    currentVersion: currentVersion,
                    latestVersion: plan.latestVersion,
                    download: downloadText,
                    files: plan.changedItemCount,
                    skipped: plan.skippedItemCount
                )
                self.lastPlanSummary = summary
                self.appendUpdateLogLine(self.logText(en: "Update source: \(plan.sourceKind.rawValue)", vi: "Nguồn cập nhật: \(plan.sourceKind.rawValue)"))
                self.appendUpdateLogLine(self.logText(en: "Installed version: \(currentVersion)", vi: "Phiên bản hiện tại: \(currentVersion)"))
                self.appendUpdateLogLine(self.logText(en: "Latest version: \(plan.latestVersion)", vi: "Phiên bản mới nhất: \(plan.latestVersion)"))
                self.appendUpdateLogLine(self.logText(en: "Items to update: \(plan.changedItemCount)", vi: "Mục cần cập nhật: \(plan.changedItemCount)"))
                self.appendUpdateLogLine(self.logText(en: "Items already valid: \(plan.skippedItemCount)", vi: "Mục đã hợp lệ: \(plan.skippedItemCount)"))
                self.appendUpdateLogLine(self.logText(en: "Bytes to download: \(downloadText)", vi: "Dung lượng cần tải: \(downloadText)"))
                if plan.sourceKind == .sophon {
                    self.appendUpdateLogLine(self.logText(
                        en: "Existing Sophon assets are resolved locally by size and MD5 before chunk downloads.",
                        vi: "Asset Sophon đã có được đối chiếu local bằng size và MD5 trước khi tải chunk."
                    ))
                    self.appendUpdateLogLine(self.logText(
                        en: "Sophon downloader: high-concurrency chunk requests, in-process zstd, batched resume state.",
                        vi: "Bộ tải Sophon: tải nhiều chunk song song, giải nén zstd trong tiến trình, gom batch trạng thái resume."
                    ))
                    self.appendUpdateLogLine(self.logText(
                        en: "Bytes to write after decompression: \(ByteCountFormatter.string(fromByteCount: plan.decompressedBytesToWrite, countStyle: .file))",
                        vi: "Dung lượng ghi sau giải nén: \(ByteCountFormatter.string(fromByteCount: plan.decompressedBytesToWrite, countStyle: .file))"
                    ))
                }
                self.appendUpdateLogLine(self.logText(en: "Peak temporary bytes: \(ByteCountFormatter.string(fromByteCount: plan.peakTemporaryBytes, countStyle: .file))", vi: "Bộ nhớ tạm tối đa: \(ByteCountFormatter.string(fromByteCount: plan.peakTemporaryBytes, countStyle: .file))"))
                self.appendUpdateLogLine(self.logText(en: "Metadata rewrite needed: \(plan.metadataNeedsUpdate ? "yes" : "no")", vi: "Cần ghi lại metadata: \(plan.metadataNeedsUpdate ? "có" : "không")"))
                self.appendPlannedUpdateItemsToLog(plan)

                if plan.isUpToDate {
                    self.statusText = self.text.gameUpToDate(plan.latestVersion)
                    self.appendUpdateLogLine(self.logText(en: "---- up to date ----", vi: "---- đã là bản mới nhất ----"))
                    self.appendUpdateLogLine(self.text.gameUpToDate(plan.latestVersion))
                    self.operationProgress = OperationProgress(
                        stageTitle: self.text.updateGameTitle,
                        itemPath: game.displayName,
                        partText: nil,
                        detailText: self.text.gameUpToDate(plan.latestVersion),
                        fractionCompleted: 1,
                        isIndeterminate: false,
                        currentPartDetailText: nil,
                        currentPartFractionCompleted: nil,
                        currentPartIsIndeterminate: false,
                        speedText: nil,
                        etaText: nil,
                        totalKBText: nil,
                        currentPartKBText: nil
                    )
                    return
                }

                self.statusText = self.text.updating(game.displayName)
                self.appendUpdateLogLine(self.logText(en: "---- apply delta ----", vi: "---- áp dụng phần cần cập nhật ----"))
                self.operationProgress = OperationProgress(
                    stageTitle: self.text.updateGameTitle,
                    itemPath: game.displayName,
                    partText: nil,
                    detailText: summary,
                    fractionCompleted: plan.bytesToDownload > 0 ? 0 : nil,
                    isIndeterminate: plan.bytesToDownload <= 0,
                    currentPartDetailText: nil,
                    currentPartFractionCompleted: nil,
                    currentPartIsIndeterminate: true,
                    speedText: nil,
                    etaText: nil,
                    totalKBText: self.text.progressValueKB(
                        receivedKB: "0",
                        totalKB: String(plan.bytesToDownload / 1024)
                    ),
                    currentPartKBText: nil
                )

                try await self.coordinator.updateGame(
                    game,
                    settings: self.settings,
                    plan: plan,
                    operationController: self.operationController
                ) { [weak self] event in
                    await MainActor.run {
                        self?.apply(event: event)
                    }
                }

                self.statusText = self.text.updateCompleted
                self.appendUpdateLogLine(self.logText(en: "---- update completed ----", vi: "---- cập nhật hoàn tất ----"))
                self.appendUpdateLogLine(self.text.updatedVersion(plan.latestVersion))
                self.operationProgress = OperationProgress(
                    stageTitle: self.text.updateGameTitle,
                    itemPath: game.displayName,
                    partText: nil,
                    detailText: self.text.updatedVersion(plan.latestVersion),
                    fractionCompleted: 1,
                    isIndeterminate: false,
                    currentPartDetailText: nil,
                    currentPartFractionCompleted: nil,
                    currentPartIsIndeterminate: false,
                    speedText: nil,
                    etaText: nil,
                    totalKBText: nil,
                    currentPartKBText: nil
                )
            } catch {
                if error is CancellationError {
                    self.statusText = self.text.operationStopped
                    self.appendUpdateLogLine(self.logText(en: "---- update stopped ----", vi: "---- đã dừng cập nhật ----"))
                } else {
                    let message = self.text.message(for: error)
                    self.errorMessage = message
                    self.statusText = self.text.updateFailed
                    self.appendUpdateLogLine(self.logText(en: "---- update failed ----", vi: "---- cập nhật thất bại ----"))
                    self.appendUpdateLogLine(message)
                }
                self.operationProgress = nil
            }
        }
    }

    /// Updates the selected game install root and derived Wine prefix path.
    func setInstallDirectoryForSelectedGame(_ url: URL) {
        updateSelectedGame { game in
            game.installDirectory = url
            game.winePrefixDirectory = url.appendingPathComponent(".wine", isDirectory: true)
        }
        persistSettings()
    }

    /// Launches the selected game through Wine.
    func launchSelectedGame() {
        guard let game = selectedGame else { return }
        resetTransferMetricsDisplay()
        currentTask?.cancel()
        isBusy = true
        isPaused = false
        isLaunchingWithWine = true
        discardBufferedRunLogs()
        wineLogBuffer.reset()
        wineRunLog = ""
        wineLogFilter.reset()
        operationController = OperationController()
        operationProgress = OperationProgress(
            stageTitle: text.launchTitle,
            itemPath: game.executableRelativePath,
            partText: nil,
            detailText: nil,
            fractionCompleted: nil,
            isIndeterminate: true,
            currentPartDetailText: nil,
            currentPartFractionCompleted: nil,
            currentPartIsIndeterminate: true,
            speedText: nil,
            etaText: nil,
            totalKBText: nil,
            currentPartKBText: nil
        )
        statusText = text.launching(game.displayName)
        errorMessage = nil
        appendWineLogLine("Launching \(game.displayName)")
        appendWineLogLine("Wine: \(settings.wineBinaryPath)")
        appendWineLogLine("Prefix: \(game.winePrefixDirectory.path)")
        appendWineLogLine("Working directory: \(game.installDirectory.path)")
        appendWineLogLine("Executable: \(game.installDirectory.appendingPathComponent(game.executableRelativePath).path)")
        appendWineLogLine("Display mode: \(settings.launchDisplayMode.rawValue)")
        let profile = LaunchRuntimeProfile.build(game: game, settings: settings)
        appendWineLogLine("Runtime backend: \(profile.backend.rawValue)")
        appendWineLogLine("Environment: \(profile.environment.sorted(by: { $0.key < $1.key }).map { "\($0.key)=\($0.value)" }.joined(separator: ", "))")
        if !game.runtimeRequirements.isEmpty {
            appendWineLogLine("Runtime requirements: \(game.runtimeRequirements.map(\.rawValue).joined(separator: ", "))")
        }
        let effectiveArguments = settings.launchArguments(for: game)
        if !effectiveArguments.isEmpty {
            appendWineLogLine("Arguments: \(effectiveArguments.joined(separator: " "))")
        }
        appendWineLogLine("---- process output ----")

        currentTask = Task { [weak self] in
            guard let self else { return }
            defer {
                self.isBusy = false
                self.isPaused = false
                self.isLaunchingWithWine = false
                self.currentTask = nil
                self.operationController = nil
                self.flushRunLogs()
            }
            do {
                let result = try await self.coordinator.launchGame(game, settings: self.settings) { [weak self] chunk in
                    Task { @MainActor [weak self] in
                        self?.appendWineLogChunk(chunk)
                    }
                }
                self.appendWineLogLine("---- process exited with code \(result.exitCode) ----")
                self.statusText = self.text.gameExitedNormally
                self.operationProgress = OperationProgress(
                    stageTitle: self.text.launchTitle,
                    itemPath: game.executableRelativePath,
                    partText: nil,
                    detailText: self.text.gameExitedNormally,
                    fractionCompleted: 1,
                    isIndeterminate: false,
                    currentPartDetailText: nil,
                    currentPartFractionCompleted: nil,
                    currentPartIsIndeterminate: false,
                    speedText: nil,
                    totalKBText: nil,
                    currentPartKBText: nil
                )
            } catch {
                if error is CancellationError {
                    self.appendWineLogLine("---- launch stopped by user ----")
                    self.statusText = self.text.operationStopped
                } else {
                    self.appendWineLogLine("---- launch failed ----")
                    self.appendWineLogLine(self.text.message(for: error))
                    self.errorMessage = self.text.message(for: error)
                    self.statusText = self.text.launchFailed
                }
                self.operationProgress = nil
            }
        }
    }

    /// Pauses or resumes the active Sophon operation.
    func togglePause() {
        guard isBusy, let operationController else { return }
        let newPausedValue = !isPaused
        isPaused = newPausedValue
        Task {
            if newPausedValue {
                await operationController.pause()
            } else {
                await operationController.resume()
            }
        }
        statusText = newPausedValue ? text.operationPaused : text.operationResumed
        if isUpdatingGame {
            appendUpdateLogLine(newPausedValue
                ? logText(en: "Pause requested", vi: "Đã yêu cầu tạm dừng")
                : logText(en: "Resume requested", vi: "Đã yêu cầu tiếp tục")
            )
        }
    }

    /// Stops the active operation.
    func stopCurrentOperation() {
        guard isBusy else { return }
        resetTransferMetricsDisplay()
        Task {
            await operationController?.stop()
        }
        if isLaunchingWithWine, let game = selectedGame {
            appendWineLogLine("---- stop requested ----")
            // Cancelling the launch SIGTERMs the Wine wrapper, but the game may
            // survive under wineserver; terminate the game processes themselves so
            // the "stopped" state truly means stopped.
            let coordinator = self.coordinator
            currentTask?.cancel()
            Task {
                await coordinator.terminateRunningGame(game)
            }
        } else {
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "---- stop requested ----", vi: "---- đã yêu cầu dừng ----"))
            }
            currentTask?.cancel()
        }
        statusText = text.operationStopped
        isPaused = false
        operationProgress = nil
    }

    /// Appends one complete line to the Wine run log.
    private func appendWineLogLine(_ line: String) {
        appendWineLogText(line + "\n")
    }

    /// Appends a streamed process chunk to the Wine run log.
    private func appendWineLogChunk(_ chunk: ProcessOutputChunk) {
        guard let text = wineLogFilter.filtered(chunk) else { return }
        appendWineLogText(text)
    }

    /// Queues Wine diagnostics for the next coalesced flush.
    private func appendWineLogText(_ text: String) {
        emitConsoleLog(channel: "wine", text: text)
        wineLogBuffer.append(text)
        scheduleRunLogFlush()
    }

    /// Appends one complete line to the update log.
    private func appendUpdateLogLine(_ line: String) {
        appendUpdateLogText(line + "\n")
    }

    /// Queues update diagnostics for the next coalesced flush.
    private func appendUpdateLogText(_ text: String) {
        emitConsoleLog(channel: "update", text: text)
        updateLogBuffer.append(text)
        scheduleRunLogFlush()
    }

    /// Publishes buffered log text on a timer instead of on every process output chunk.
    ///
    /// A running game emits Wine diagnostics continuously, and each published change re-lays out
    /// the whole log `Text` (SwiftUI does not virtualize it) on the main thread the game is
    /// competing with. Coalescing turns hundreds of layout passes per second into a handful.
    private func scheduleRunLogFlush() {
        guard runLogFlushTask == nil else { return }
        runLogFlushTask = Task { [weak self] in
            try? await Task.sleep(nanoseconds: Self.runLogFlushInterval)
            guard !Task.isCancelled else { return }
            self?.flushRunLogs()
        }
    }

    /// Publishes whatever the buffers have accumulated since the last flush.
    private func flushRunLogs() {
        runLogFlushTask?.cancel()
        runLogFlushTask = nil
        guard wineLogBuffer.hasPendingText || updateLogBuffer.hasPendingText else { return }

        if wineLogBuffer.flush() {
            wineRunLog = wineLogBuffer.contents
        }
        if updateLogBuffer.flush() {
            updateRunLog = updateLogBuffer.contents
        }
        runLogVersion &+= 1
    }

    /// Drops buffered text and any pending flush, so a new run never inherits the previous tail.
    private func discardBufferedRunLogs() {
        runLogFlushTask?.cancel()
        runLogFlushTask = nil
        wineLogBuffer.discardPending()
        updateLogBuffer.discardPending()
    }

    /// Mirrors app-visible logs to stdout so terminal and Xcode console runs show the same diagnostics.
    private func emitConsoleLog(channel: String, text: String) {
        let prefixed = text
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { line in
                line.isEmpty ? "" : "[NSLauncher][\(channel)] \(line)"
            }
            .joined(separator: "\n")

        guard !prefixed.isEmpty,
              let data = prefixed.data(using: .utf8) else { return }
        FileHandle.standardOutput.write(data)
    }

    /// Localizes compact diagnostic log labels without making AppText carry implementation details.
    private func logText(en: String, vi: String) -> String {
        switch settings.language {
        case .english:
            return en
        case .vietnamese:
            return vi
        }
    }

    /// Writes a bounded sample of planned update items so huge Sophon plans remain readable.
    private func appendPlannedUpdateItemsToLog(_ plan: GameUpdatePlan) {
        let assets = plan.sophonAssetsToWrite
        guard !assets.isEmpty else { return }
        appendUpdateLogLine(logText(en: "Changed Sophon asset sample:", vi: "Một số asset Sophon sẽ cập nhật:"))
        for asset in assets.prefix(25) {
            let downloadText = ByteCountFormatter.string(fromByteCount: asset.compressedBytes, countStyle: .file)
            let writeText = ByteCountFormatter.string(fromByteCount: asset.size, countStyle: .file)
            appendUpdateLogLine("- \(asset.path) (\(downloadText) download, \(writeText) write) md5=\(asset.md5)")
        }
        if assets.count > 25 {
            appendUpdateLogLine(logText(en: "- ... \(assets.count - 25) more assets", vi: "- ... còn \(assets.count - 25) asset nữa"))
        }
    }

    /// Records Sophon download progress at useful milestones without flooding the UI.
    private func appendUpdateProgressLog(path: String, overallReceived: Int64, overallTotal: Int64, fileReceived: Int64, fileTotal: Int64) {
        guard isUpdatingGame else { return }

        if fileReceived == 0 {
            appendUpdateLogLine(logText(
                en: "[download] start \(path) (\(ByteCountFormatter.string(fromByteCount: fileTotal, countStyle: .file)))",
                vi: "[download] bắt đầu \(path) (\(ByteCountFormatter.string(fromByteCount: fileTotal, countStyle: .file)))"
            ))
            return
        }

        if fileTotal > 0, fileReceived >= fileTotal, !updateLoggedCompletedFiles.contains(path) {
            updateLoggedCompletedFiles.insert(path)
            appendUpdateLogLine(logText(en: "[download] completed \(path)", vi: "[download] xong \(path)"))
            return
        }

        guard overallTotal > 0 else { return }
        let bucket = Int((Double(overallReceived) / Double(overallTotal) * 100).rounded(.down) / 5) * 5
        guard bucket > 0, bucket < 100, bucket != lastUpdateLogOverallBucket else { return }
        lastUpdateLogOverallBucket = bucket
        let receivedText = ByteCountFormatter.string(fromByteCount: overallReceived, countStyle: .file)
        let totalText = ByteCountFormatter.string(fromByteCount: overallTotal, countStyle: .file)
        appendUpdateLogLine(logText(en: "[progress] \(bucket)% (\(receivedText) / \(totalText))", vi: "[tiến độ] \(bucket)% (\(receivedText) / \(totalText))"))
    }

    /// Maps service-layer progress events into stable UI state.
    private func apply(event: InstallProgressEvent) {
        switch event {
        case let .diagnostic(message):
            if isUpdatingGame {
                appendUpdateLogLine("[detail] \(message)")
            }
        case let .preparing(path):
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "[prepare] \(path)", vi: "[chuẩn bị] \(path)"))
            }
            statusText = text.preparing(path)
            operationProgress = OperationProgress(
                stageTitle: text.preparingStage,
                itemPath: path,
                partText: nil,
                detailText: nil,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .downloadingSophonAsset(path, overallReceived, overallTotal, fileReceived, fileTotal):
            appendUpdateProgressLog(
                path: path,
                overallReceived: overallReceived,
                overallTotal: overallTotal,
                fileReceived: fileReceived,
                fileTotal: fileTotal
            )
            let overallReceivedText = ByteCountFormatter.string(fromByteCount: overallReceived, countStyle: .file)
            let overallTotalText = ByteCountFormatter.string(fromByteCount: overallTotal, countStyle: .file)
            let fileReceivedText = ByteCountFormatter.string(fromByteCount: fileReceived, countStyle: .file)
            let fileTotalText = ByteCountFormatter.string(fromByteCount: fileTotal, countStyle: .file)
            let overallFraction = overallTotal > 0 ? min(max(Double(overallReceived) / Double(overallTotal), 0), 1) : nil
            let fileFraction = fileTotal > 0 ? min(max(Double(fileReceived) / Double(fileTotal), 0), 1) : nil
            let now = Date()
            let estimate = transferRate.update(received: overallReceived, total: overallTotal, now: now)
            let latestSpeedText = estimate.speedBytesPerSecond.map {
                ByteCountFormatter.string(fromByteCount: $0, countStyle: .file) + "/s"
            }
            // The ETA is withheld until the rolling window has warmed up; an estimate off the first
            // second of a multi-gigabyte download is wrong by hours.
            let latestEtaText = estimate.isWarmupComplete
                ? estimate.etaSeconds.flatMap(ETAFormatter.text(seconds:))
                : nil
            let transferMetrics = transferMetricsThrottle.display(
                speedText: latestSpeedText,
                etaText: latestEtaText,
                now: now
            )
            let latestDetailText = progressDetailText(
                receivedText: overallReceivedText,
                totalText: overallTotalText,
                fraction: overallFraction
            )
            let latestCurrentPartDetailText = progressDetailText(
                receivedText: fileReceivedText,
                totalText: fileTotalText,
                fraction: fileFraction
            )
            let latestTotalKBText = text.progressValueKB(
                receivedKB: String(overallReceived / 1024),
                totalKB: String(overallTotal / 1024)
            )
            let latestCurrentPartKBText = text.progressValueKB(
                receivedKB: String(fileReceived / 1024),
                totalKB: String(fileTotal / 1024)
            )
            let throttledFields = downloadFieldThrottle.display(
                DownloadFieldSnapshot(
                    path: path,
                    partText: nil,
                    detailText: latestDetailText,
                    currentPartDetailText: latestCurrentPartDetailText,
                    totalKBText: latestTotalKBText,
                    currentPartKBText: latestCurrentPartKBText
                ),
                now: now
            )
            let activeItems = registerActiveSophonItem(path)
            statusText = text.downloadingSophonAsset(
                path,
                received: overallReceivedText,
                total: overallTotalText
            )
            operationProgress = OperationProgress(
                stageTitle: text.downloadingStage,
                itemPath: path,
                itemPaths: activeItems,
                partText: nil,
                detailText: throttledFields.detailText,
                fractionCompleted: overallFraction,
                isIndeterminate: overallTotal <= 0,
                currentPartDetailText: throttledFields.currentPartDetailText,
                currentPartFractionCompleted: fileFraction,
                currentPartIsIndeterminate: fileTotal <= 0,
                speedText: transferMetrics.speedText,
                etaText: transferMetrics.etaText,
                isETAWarmingUp: !estimate.isWarmupComplete && overallReceived > 0,
                totalKBText: throttledFields.totalKBText,
                currentPartKBText: throttledFields.currentPartKBText
            )
        case let .verifying(path):
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "[verify] \(path)", vi: "[xác thực] \(path)"))
            }
            statusText = text.verifying(path)
            operationProgress = OperationProgress(
                stageTitle: text.verifyingStage,
                itemPath: path,
                partText: nil,
                detailText: nil,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .validatingInstall(path):
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "[validate] \(path)", vi: "[kiểm tra] \(path)"))
            }
            statusText = text.validating(path)
            operationProgress = OperationProgress(
                stageTitle: text.validatingStage,
                itemPath: path,
                partText: nil,
                detailText: nil,
                fractionCompleted: nil,
                isIndeterminate: true,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: true,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        case let .finished(version):
            if isUpdatingGame {
                appendUpdateLogLine(logText(en: "[metadata] wrote version \(version)", vi: "[metadata] đã ghi bản \(version)"))
            }
            statusText = text.installedVersion(version)
            operationProgress = OperationProgress(
                stageTitle: text.completedStage,
                itemPath: version,
                partText: nil,
                detailText: text.installedVersion(version),
                fractionCompleted: 1,
                isIndeterminate: false,
                currentPartDetailText: nil,
                currentPartFractionCompleted: nil,
                currentPartIsIndeterminate: false,
                speedText: nil,
                etaText: nil,
                totalKBText: nil,
                currentPartKBText: nil
            )
        }
    }

    /// Formats byte progress with a percent suffix when the total is known.
    private func progressDetailText(receivedText: String, totalText: String, fraction: Double?) -> String {
        let byteText = text.progressValue(received: receivedText, total: totalText)
        guard let fraction else { return byteText }
        let percent = NumberFormatter.localizedString(
            from: NSNumber(value: min(max(fraction, 0), 1)),
            number: .percent
        )
        return "\(byteText) (\(percent))"
    }

    /// Clears cached transfer metrics when starting a new operation.
    private func resetTransferMetricsDisplay() {
        transferRate.reset()
        transferMetricsThrottle.reset()
        downloadFieldThrottle.reset()
    }

    /// Mutates the selected game in settings.
    private func updateSelectedGame(_ update: (inout GameDefinition) -> Void) {
        guard !settings.games.isEmpty else { return }
        update(&settings.games[0])
    }

    /// Tracks recently active Sophon assets for the multi-file progress list.
    private func registerActiveSophonItem(_ path: String) -> [String] {
        let now = Date()
        activeSophonItems[path] = now
        activeSophonItems = activeSophonItems.filter { now.timeIntervalSince($0.value) < 2.5 }
        return activeSophonItems
            .sorted { $0.value > $1.value }
            .map(\.key)
            .prefix(16)
            .map { $0 }
    }

    /// Clears the Sophon activity list between operations.
    private func resetActiveSophonItems() {
        activeSophonItems.removeAll()
    }
}
